/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProcessedMail } from '../../models/processed-mail';

export interface ListProcessedMails$Params {
  limit?: number;
}

export function listProcessedMails(http: HttpClient, rootUrl: string, params?: ListProcessedMails$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProcessedMail>>> {
  const rb = new RequestBuilder(rootUrl, listProcessedMails.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProcessedMail>>;
    })
  );
}

listProcessedMails.PATH = '/api/v1/processed-mails';
