/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Suggestion } from '../../models/suggestion';

export interface ListSuggestions$Params {
}

export function listSuggestions(http: HttpClient, rootUrl: string, params?: ListSuggestions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Suggestion>>> {
  const rb = new RequestBuilder(rootUrl, listSuggestions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Suggestion>>;
    })
  );
}

listSuggestions.PATH = '/api/v1/suggestions';
