/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentsState } from '../models/documents-state';
export interface AgentApplication {
  company_name: string;
  company_website?: string;
  contact_email?: string;
  documents_state: DocumentsState;

  /**
   * 0 = noch keine Unterlagen; zu liefern ist documents_version + 1
   */
  documents_version: number;
  fit_reason?: string;
  id: string;
  job_url?: string;
  location?: string;
  position_title: string;
  posting_text?: string;
}
