/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AgentJob {
  company_name: string;
  company_website?: string;
  contact_email?: string;
  fit_reason: string;
  fit_score: number;
  job_url?: string;
  location?: string;
  position_title: string;
  posting_text?: string;
  source?: string;
}
