/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentsInput } from '../models/documents-input';
export type AgentDocumentsInput = DocumentsInput & {
'version': number;
};

