/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Event } from '../models/event';
import { EventType } from '../models/event-type';
import { Phase } from '../models/phase';
export interface Application {
  company_id: string;
  company_name: string;
  contact_email?: string;
  created_at: string;
  created_by_agent: boolean;
  events: Array<Event>;
  fit_reason?: string;
  fit_score?: number;
  id: string;
  job_url?: string;
  location?: string;
  notes?: string;
  phase: Phase;
  position_title: string;
  posting_text?: string;
  source?: string;
  status: EventType;
  updated_at: string;
}
