/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewEvent } from '../models/new-event';
export interface ApplicationInput {
  company_id: string;
  first_event: NewEvent;
  job_url?: string;
  location?: string;
  notes?: string;
  position_title: string;
  source?: string;
}
