/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Nur gesetzte Felder werden geändert; ein leerer String löscht ein optionales Feld.
 */
export interface ApplicationPatch {
  company_id?: string;
  contact_email?: string;
  job_url?: string;
  location?: string;
  notes?: string;
  position_title?: string;
  source?: string;
}
