/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
import { Phase } from '../models/phase';
export interface ApplicationSummary {
  company_id: string;
  company_name: string;
  id: string;
  last_event_on: string;
  open_due_on?: string;
  phase: Phase;
  position_title: string;
  status: EventType;
  updated_at: string;
}
