/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
export interface Appointment {
  application_id: string;
  company_name: string;
  date: string;
  event_type: EventType;
  interview_round?: number;
  position_title: string;
}
