/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Company {
  application_count: number;
  created_at: string;
  id: string;
  name: string;
  notes?: string;
  website?: string;
}
