/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Nur gesetzte Felder werden geändert; ein leerer String löscht ein optionales Feld.
 */
export interface CompanyPatch {
  name?: string;
  notes?: string;
  website?: string;
}
