/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CvPeriod } from '../models/cv-period';
export interface CvExperience {
  end?: CvPeriod;
  highlights: Array<string>;
  location?: string;
  organization: string;
  role: string;
  start: CvPeriod;
}
