/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CvPeriod } from '../models/cv-period';
export interface CvEducation {
  degree: string;
  details?: string;
  end?: CvPeriod;
  institution: string;
  start: CvPeriod;
}
