/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CvLink } from '../models/cv-link';
export interface CvPerson {
  email?: string;
  headline?: string;
  links: Array<CvLink>;
  location?: string;
  name: string;
  phone?: string;
}
