/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CvReviewState } from './cv-review-state';

/**
 * Each possible value of `CvReviewState`
 */
export const CV_REVIEW_STATE: CvReviewState[] = [
  'angefordert',
  'fertig',
  'abgeschlossen'
];