/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cv } from '../models/cv';
import { CvReviewState } from '../models/cv-review-state';

/**
 * Optimierungslauf; proposal fehlt, solange er angefordert ist.
 */
export interface CvReview {

  /**
   * Stand des Lebenslaufs bei der Anforderung
   */
  based_on_updated_at: string;
  completed_at?: string;
  id: string;
  notes: Array<string>;
  proposal?: Cv;
  requested_at: string;
  state: CvReviewState;
}
