/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
export interface Deadline {
  application_id: string;
  company_name: string;
  due_on: string;
  event_type: EventType;
  overdue: boolean;
  position_title: string;
}
