/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentsState } from './documents-state';

/**
 * Each possible value of `DocumentsState`
 */
export const DOCUMENTS_STATE: DocumentsState[] = [
  'keine',
  'angefordert',
  'erstellt',
  'entwurf_angelegt',
  'portal',
  'fehler'
];