/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentsInput {
  cover_letter: string;
  highlights?: Array<string>;
  language: 'de' | 'en';
  mail_body: string;
  mail_subject: string;
  profile_line?: string;
}
