/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Documents {
  cover_letter: string;
  file_name?: string;
  highlights: Array<string>;
  language: 'de' | 'en';
  mail_body: string;
  mail_subject: string;
  profile_line?: string;
  rendered_at?: string;
  updated_at: string;
  version: number;
}
