/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
export interface Event {
  created_at: string;
  due_on?: string;
  id: string;
  interview_round?: number;
  note?: string;
  occurred_on: string;
  type: EventType;
}
