/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from './event-type';

/**
 * Each possible value of `EventType`
 */
export const EVENT_TYPE: EventType[] = [
  'Vorgemerkt',
  'Beworben',
  'ScreeningGespraech',
  'ChallengeErhalten',
  'ChallengeAbgegeben',
  'Interview',
  'Kennenlerntag',
  'AngebotErhalten',
  'AngebotAngenommen',
  'AngebotAbgelehnt',
  'Absage',
  'Zurueckgezogen',
  'KeineRueckmeldung'
];