/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentsState } from '../models/documents-state';
import { EventType } from '../models/event-type';
export interface OpenApplication {
  allowed_events: Array<EventType>;
  company_name: string;
  company_website?: string;
  contact_email?: string;
  documents_state: DocumentsState;
  gmail_draft_at?: string;
  gmail_thread_id?: string;
  id: string;

  /**
   * Betreff der Bewerbungsmail aus den Unterlagen, falls vorhanden
   */
  mail_subject?: string;
  position_title: string;
  status: EventType;
}
