/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Phase } from './phase';

/**
 * Each possible value of `Phase`
 */
export const PHASE: Phase[] = [
  'Vorbereitung',
  'Aktiv',
  'Abgeschlossen'
];