/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
export interface Problem {
  attempted?: EventType;
  detail?: string;
  field?: string;
  from?: EventType;
  status: number;
  title: string;
  type: string;

  [key: string]: any;
}
