/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GmailMessageId } from '../models/gmail-message-id';
export interface ProcessedMailInput {
  application_id?: string;
  gmail_message_id: GmailMessageId;
  outcome: string;
}
