/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProcessedMail {
  application_id?: string;
  gmail_message_id: string;
  outcome: string;
  processed_at: string;
}
