/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
export interface RejectionCount {
  count: number;
  event_type: EventType;
}
