/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SuggestionState } from './suggestion-state';

/**
 * Each possible value of `SuggestionState`
 */
export const SUGGESTION_STATE: SuggestionState[] = [
  'offen',
  'angenommen',
  'verworfen'
];