/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
import { SuggestionState } from '../models/suggestion-state';
export interface Suggestion {
  application_id?: string;
  company_name?: string;
  created_at: string;
  decided_at?: string;
  due_on?: string;
  id: string;
  mail_from?: string;
  mail_subject?: string;
  mail_url?: string;
  occurred_on: string;
  position_title?: string;
  reason: string;
  state: SuggestionState;
  suggested_type: EventType;
}
