/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SuggestionAccept {

  /**
   * Pflicht bei nicht zugeordneten Vorschlägen; sonst Vorrang vor der Zuordnung
   */
  application_id?: string;
}
