/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
import { GmailMessageId } from '../models/gmail-message-id';
export interface SuggestionInput {
  application_id?: string;
  due_on?: string;

  /**
   * Mail, aus der der Vorschlag stammt; je Mail höchstens ein Vorschlag
   */
  gmail_message_id?: GmailMessageId;
  mail_from?: string;
  mail_subject?: string;
  mail_url?: string;
  occurred_on: string;
  reason: string;
  suggested_type: EventType;
}
