/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
export interface SuggestionInput {
  application_id?: string;
  due_on?: string;
  mail_from?: string;
  mail_subject?: string;
  mail_url?: string;
  occurred_on: string;
  reason: string;
  suggested_type: EventType;
}
