/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RejectionCount } from '../models/rejection-count';
import { SourceStats } from '../models/source-stats';
export interface Summary {
  applied: number;
  avg_days_to_response?: number;
  by_source: Array<SourceStats>;
  median_days_to_response?: number;
  rejections_after: Array<RejectionCount>;
  responded: number;
  response_rate: number;
}
