/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationSummary } from '../../models/application-summary';
import { EventType } from '../../models/event-type';
import { Phase } from '../../models/phase';

export interface ListApplications$Params {
  phase?: Phase;
  status?: EventType;

/**
 * Suche in Firmenname und Stellentitel
 */
  q?: string;

/**
 * true = nur vom Agenten angelegte, false = nur manuell angelegte
 */
  from_agent?: boolean;

/**
 * updated (Standard) = zuletzt geändert zuerst, score = beste Passung zuerst
 */
  sort?: 'updated' | 'score';
}

export function listApplications(http: HttpClient, rootUrl: string, params?: ListApplications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ApplicationSummary>>> {
  const rb = new RequestBuilder(rootUrl, listApplications.PATH, 'get');
  if (params) {
    rb.query('phase', params.phase, {});
    rb.query('status', params.status, {});
    rb.query('q', params.q, {});
    rb.query('from_agent', params.from_agent, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ApplicationSummary>>;
    })
  );
}

listApplications.PATH = '/api/v1/applications';
