/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventType } from '../../models/event-type';

export interface ListAllowedEvents$Params {
  id: string;
}

export function listAllowedEvents(http: HttpClient, rootUrl: string, params: ListAllowedEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EventType>>> {
  const rb = new RequestBuilder(rootUrl, listAllowedEvents.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EventType>>;
    })
  );
}

listAllowedEvents.PATH = '/api/v1/applications/{id}/allowed-events';
