/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CvReview } from '../../models/cv-review';

export interface GetCvReview$Params {
}

export function getCvReview(http: HttpClient, rootUrl: string, params?: GetCvReview$Params, context?: HttpContext): Observable<StrictHttpResponse<CvReview>> {
  const rb = new RequestBuilder(rootUrl, getCvReview.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CvReview>;
    })
  );
}

getCvReview.PATH = '/api/v1/cv/review';
