/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cv } from '../../models/cv';

export interface GetCv$Params {
}

export function getCv(http: HttpClient, rootUrl: string, params?: GetCv$Params, context?: HttpContext): Observable<StrictHttpResponse<Cv>> {
  const rb = new RequestBuilder(rootUrl, getCv.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Cv>;
    })
  );
}

getCv.PATH = '/api/v1/cv';
