/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cv } from '../../models/cv';

export interface SaveCv$Params {
      body: Cv
}

export function saveCv(http: HttpClient, rootUrl: string, params: SaveCv$Params, context?: HttpContext): Observable<StrictHttpResponse<Cv>> {
  const rb = new RequestBuilder(rootUrl, saveCv.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Cv>;
    })
  );
}

saveCv.PATH = '/api/v1/cv';
