/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Documents } from '../../models/documents';
import { DocumentsInput } from '../../models/documents-input';

export interface UpdateDocuments$Params {
  id: string;
      body: DocumentsInput
}

export function updateDocuments(http: HttpClient, rootUrl: string, params: UpdateDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Documents>> {
  const rb = new RequestBuilder(rootUrl, updateDocuments.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Documents>;
    })
  );
}

updateDocuments.PATH = '/api/v1/applications/{id}/documents';
