/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { agentCompleteCvReview } from '../fn/agent/agent-complete-cv-review';
import { AgentCompleteCvReview$Params } from '../fn/agent/agent-complete-cv-review';
import { agentGetCv } from '../fn/agent/agent-get-cv';
import { AgentGetCv$Params } from '../fn/agent/agent-get-cv';
import { agentListCvReviews } from '../fn/agent/agent-list-cv-reviews';
import { AgentListCvReviews$Params } from '../fn/agent/agent-list-cv-reviews';
import { Cv } from '../models/cv';
import { CvReview } from '../models/cv-review';


/**
 * Für Claude-Agenten; verlangt Authorization: Bearer <AGENT_TOKEN>
 */
@Injectable({ providedIn: 'root' })
export class AgentService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `agentGetCv()` */
  static readonly AgentGetCvPath = '/api/agent/cv';

  /**
   * Gespeicherter Lebenslauf (404, solange keiner gespeichert ist).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agentGetCv()` instead.
   *
   * This method doesn't expect any request body.
   */
  agentGetCv$Response(params?: AgentGetCv$Params, context?: HttpContext): Observable<StrictHttpResponse<Cv>> {
    const obs = agentGetCv(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Gespeicherter Lebenslauf (404, solange keiner gespeichert ist).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agentGetCv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agentGetCv(params?: AgentGetCv$Params, context?: HttpContext): Observable<Cv> {
    const resp = this.agentGetCv$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Cv>): Cv => r.body)
    );
  }

  /** Path part for operation `agentListCvReviews()` */
  static readonly AgentListCvReviewsPath = '/api/agent/cv-reviews';

  /**
   * Optimierungen in einem Zustand (für den Agenten meist „angefordert“).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agentListCvReviews()` instead.
   *
   * This method doesn't expect any request body.
   */
  agentListCvReviews$Response(params: AgentListCvReviews$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CvReview>>> {
    const obs = agentListCvReviews(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Optimierungen in einem Zustand (für den Agenten meist „angefordert“).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agentListCvReviews$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agentListCvReviews(params: AgentListCvReviews$Params, context?: HttpContext): Observable<Array<CvReview>> {
    const resp = this.agentListCvReviews$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<CvReview>>): Array<CvReview> => r.body)
    );
  }

  /** Path part for operation `agentCompleteCvReview()` */
  static readonly AgentCompleteCvReviewPath = '/api/agent/cv-reviews/{id}';

  /**
   * Vorschlag und Hinweise abliefern (409, wenn nicht angefordert).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agentCompleteCvReview()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agentCompleteCvReview$Response(params: AgentCompleteCvReview$Params, context?: HttpContext): Observable<StrictHttpResponse<CvReview>> {
    const obs = agentCompleteCvReview(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Vorschlag und Hinweise abliefern (409, wenn nicht angefordert).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agentCompleteCvReview$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agentCompleteCvReview(params: AgentCompleteCvReview$Params, context?: HttpContext): Observable<CvReview> {
    const resp = this.agentCompleteCvReview$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CvReview>): CvReview => r.body)
    );
  }

}
