/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AgentApplication } from '../models/agent-application';
import { agentCompleteCvReview } from '../fn/agent/agent-complete-cv-review';
import { AgentCompleteCvReview$Params } from '../fn/agent/agent-complete-cv-review';
import { agentCreateApplication } from '../fn/agent/agent-create-application';
import { AgentCreateApplication$Params } from '../fn/agent/agent-create-application';
import { agentGetCv } from '../fn/agent/agent-get-cv';
import { AgentGetCv$Params } from '../fn/agent/agent-get-cv';
import { agentListApplications } from '../fn/agent/agent-list-applications';
import { AgentListApplications$Params } from '../fn/agent/agent-list-applications';
import { agentListCvReviews } from '../fn/agent/agent-list-cv-reviews';
import { AgentListCvReviews$Params } from '../fn/agent/agent-list-cv-reviews';
import { agentPutDocuments } from '../fn/agent/agent-put-documents';
import { AgentPutDocuments$Params } from '../fn/agent/agent-put-documents';
import { Application } from '../models/application';
import { Cv } from '../models/cv';
import { CvReview } from '../models/cv-review';
import { Documents } from '../models/documents';


/**
 * Für Claude-Agenten; verlangt Authorization: Bearer <AGENT_TOKEN>
 */
@Injectable({ providedIn: 'root' })
export class AgentService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `agentGetCv()` */
  static readonly AgentGetCvPath = '/api/agent/cv';

  /**
   * Gespeicherter Lebenslauf (404, solange keiner gespeichert ist).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agentGetCv()` instead.
   *
   * This method doesn't expect any request body.
   */
  agentGetCv$Response(params?: AgentGetCv$Params, context?: HttpContext): Observable<StrictHttpResponse<Cv>> {
    const obs = agentGetCv(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Gespeicherter Lebenslauf (404, solange keiner gespeichert ist).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agentGetCv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agentGetCv(params?: AgentGetCv$Params, context?: HttpContext): Observable<Cv> {
    const resp = this.agentGetCv$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Cv>): Cv => r.body)
    );
  }

  /** Path part for operation `agentListCvReviews()` */
  static readonly AgentListCvReviewsPath = '/api/agent/cv-reviews';

  /**
   * Optimierungen in einem Zustand (für den Agenten meist „angefordert“).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agentListCvReviews()` instead.
   *
   * This method doesn't expect any request body.
   */
  agentListCvReviews$Response(params: AgentListCvReviews$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CvReview>>> {
    const obs = agentListCvReviews(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Optimierungen in einem Zustand (für den Agenten meist „angefordert“).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agentListCvReviews$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agentListCvReviews(params: AgentListCvReviews$Params, context?: HttpContext): Observable<Array<CvReview>> {
    const resp = this.agentListCvReviews$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<CvReview>>): Array<CvReview> => r.body)
    );
  }

  /** Path part for operation `agentCompleteCvReview()` */
  static readonly AgentCompleteCvReviewPath = '/api/agent/cv-reviews/{id}';

  /**
   * Vorschlag und Hinweise abliefern (409, wenn nicht angefordert).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agentCompleteCvReview()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agentCompleteCvReview$Response(params: AgentCompleteCvReview$Params, context?: HttpContext): Observable<StrictHttpResponse<CvReview>> {
    const obs = agentCompleteCvReview(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Vorschlag und Hinweise abliefern (409, wenn nicht angefordert).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agentCompleteCvReview$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agentCompleteCvReview(params: AgentCompleteCvReview$Params, context?: HttpContext): Observable<CvReview> {
    const resp = this.agentCompleteCvReview$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CvReview>): CvReview => r.body)
    );
  }

  /** Path part for operation `agentListApplications()` */
  static readonly AgentListApplicationsPath = '/api/agent/applications';

  /**
   * Stellen in einem Unterlagen-Zustand (für den Agenten meist „angefordert“), älteste zuerst.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agentListApplications()` instead.
   *
   * This method doesn't expect any request body.
   */
  agentListApplications$Response(params: AgentListApplications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AgentApplication>>> {
    const obs = agentListApplications(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stellen in einem Unterlagen-Zustand (für den Agenten meist „angefordert“), älteste zuerst.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agentListApplications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  agentListApplications(params: AgentListApplications$Params, context?: HttpContext): Observable<Array<AgentApplication>> {
    const resp = this.agentListApplications$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<AgentApplication>>): Array<AgentApplication> => r.body)
    );
  }

  /** Path part for operation `agentCreateApplication()` */
  static readonly AgentCreateApplicationPath = '/api/agent/applications';

  /**
   * Gefundene Stelle als Vorgemerkt anlegen.
   *
   * Dublette (gleiche Anzeigen-URL oder gleiche Firma + Titel) → 409 mit `existing_id`.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agentCreateApplication()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agentCreateApplication$Response(params: AgentCreateApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<Application>> {
    const obs = agentCreateApplication(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Gefundene Stelle als Vorgemerkt anlegen.
   *
   * Dublette (gleiche Anzeigen-URL oder gleiche Firma + Titel) → 409 mit `existing_id`.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agentCreateApplication$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agentCreateApplication(params: AgentCreateApplication$Params, context?: HttpContext): Observable<Application> {
    const resp = this.agentCreateApplication$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Application>): Application => r.body)
    );
  }

  /** Path part for operation `agentPutDocuments()` */
  static readonly AgentPutDocumentsPath = '/api/agent/applications/{id}/documents';

  /**
   * Unterlagen abliefern; der Server rendert das PDF und legt ggf. den Gmail-Entwurf an.
   *
   * `version` = `documents_version` + 1. Eine erneute, gleiche Lieferung derselben Version ist ein No-op (200). 409, wenn keine Unterlagen angefordert sind, kein Lebenslauf gespeichert ist oder die Version veraltet ist; 503, wenn der PDF-Dienst nicht erreichbar ist (später erneut liefern).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `agentPutDocuments()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agentPutDocuments$Response(params: AgentPutDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Documents>> {
    const obs = agentPutDocuments(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Unterlagen abliefern; der Server rendert das PDF und legt ggf. den Gmail-Entwurf an.
   *
   * `version` = `documents_version` + 1. Eine erneute, gleiche Lieferung derselben Version ist ein No-op (200). 409, wenn keine Unterlagen angefordert sind, kein Lebenslauf gespeichert ist oder die Version veraltet ist; 503, wenn der PDF-Dienst nicht erreichbar ist (später erneut liefern).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `agentPutDocuments$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  agentPutDocuments(params: AgentPutDocuments$Params, context?: HttpContext): Observable<Documents> {
    const resp = this.agentPutDocuments$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Documents>): Documents => r.body)
    );
  }

}
