/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addEvent } from '../fn/applications/add-event';
import { AddEvent$Params } from '../fn/applications/add-event';
import { Application } from '../models/application';
import { ApplicationSummary } from '../models/application-summary';
import { createApplication } from '../fn/applications/create-application';
import { CreateApplication$Params } from '../fn/applications/create-application';
import { deleteApplication } from '../fn/applications/delete-application';
import { DeleteApplication$Params } from '../fn/applications/delete-application';
import { Event } from '../models/event';
import { EventType } from '../models/event-type';
import { getApplication } from '../fn/applications/get-application';
import { GetApplication$Params } from '../fn/applications/get-application';
import { listAllowedEvents } from '../fn/applications/list-allowed-events';
import { ListAllowedEvents$Params } from '../fn/applications/list-allowed-events';
import { listApplications } from '../fn/applications/list-applications';
import { ListApplications$Params } from '../fn/applications/list-applications';
import { undoLastEvent } from '../fn/applications/undo-last-event';
import { UndoLastEvent$Params } from '../fn/applications/undo-last-event';
import { updateApplication } from '../fn/applications/update-application';
import { UpdateApplication$Params } from '../fn/applications/update-application';


/**
 * Bewerbungen und Ereignisse
 */
@Injectable({ providedIn: 'root' })
export class ApplicationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listApplications()` */
  static readonly ListApplicationsPath = '/api/v1/applications';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listApplications()` instead.
   *
   * This method doesn't expect any request body.
   */
  listApplications$Response(params?: ListApplications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ApplicationSummary>>> {
    const obs = listApplications(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listApplications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listApplications(params?: ListApplications$Params, context?: HttpContext): Observable<Array<ApplicationSummary>> {
    const resp = this.listApplications$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ApplicationSummary>>): Array<ApplicationSummary> => r.body)
    );
  }

  /** Path part for operation `createApplication()` */
  static readonly CreateApplicationPath = '/api/v1/applications';

  /**
   * Bewerbung inklusive erstem Ereignis (Vorgemerkt oder Beworben) anlegen.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createApplication()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createApplication$Response(params: CreateApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<Application>> {
    const obs = createApplication(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Bewerbung inklusive erstem Ereignis (Vorgemerkt oder Beworben) anlegen.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createApplication$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createApplication(params: CreateApplication$Params, context?: HttpContext): Observable<Application> {
    const resp = this.createApplication$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Application>): Application => r.body)
    );
  }

  /** Path part for operation `getApplication()` */
  static readonly GetApplicationPath = '/api/v1/applications/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getApplication()` instead.
   *
   * This method doesn't expect any request body.
   */
  getApplication$Response(params: GetApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<Application>> {
    const obs = getApplication(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getApplication$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getApplication(params: GetApplication$Params, context?: HttpContext): Observable<Application> {
    const resp = this.getApplication$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Application>): Application => r.body)
    );
  }

  /** Path part for operation `deleteApplication()` */
  static readonly DeleteApplicationPath = '/api/v1/applications/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteApplication()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteApplication$Response(params: DeleteApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteApplication(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteApplication$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteApplication(params: DeleteApplication$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteApplication$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateApplication()` */
  static readonly UpdateApplicationPath = '/api/v1/applications/{id}';

  /**
   * Stammdaten ändern (nicht den Status).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateApplication()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateApplication$Response(params: UpdateApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<Application>> {
    const obs = updateApplication(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Stammdaten ändern (nicht den Status).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateApplication$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateApplication(params: UpdateApplication$Params, context?: HttpContext): Observable<Application> {
    const resp = this.updateApplication$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Application>): Application => r.body)
    );
  }

  /** Path part for operation `addEvent()` */
  static readonly AddEventPath = '/api/v1/applications/{id}/events';

  /**
   * Statuswechsel als Ereignis erfassen (422 bei unerlaubtem Übergang).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addEvent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addEvent$Response(params: AddEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<Event>> {
    const obs = addEvent(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Statuswechsel als Ereignis erfassen (422 bei unerlaubtem Übergang).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addEvent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addEvent(params: AddEvent$Params, context?: HttpContext): Observable<Event> {
    const resp = this.addEvent$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Event>): Event => r.body)
    );
  }

  /** Path part for operation `undoLastEvent()` */
  static readonly UndoLastEventPath = '/api/v1/applications/{id}/events/latest';

  /**
   * Letztes Ereignis rückgängig machen.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `undoLastEvent()` instead.
   *
   * This method doesn't expect any request body.
   */
  undoLastEvent$Response(params: UndoLastEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<Application>> {
    const obs = undoLastEvent(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Letztes Ereignis rückgängig machen.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `undoLastEvent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  undoLastEvent(params: UndoLastEvent$Params, context?: HttpContext): Observable<Application> {
    const resp = this.undoLastEvent$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Application>): Application => r.body)
    );
  }

  /** Path part for operation `listAllowedEvents()` */
  static readonly ListAllowedEventsPath = '/api/v1/applications/{id}/allowed-events';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAllowedEvents()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAllowedEvents$Response(params: ListAllowedEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EventType>>> {
    const obs = listAllowedEvents(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAllowedEvents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAllowedEvents(params: ListAllowedEvents$Params, context?: HttpContext): Observable<Array<EventType>> {
    const resp = this.listAllowedEvents$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<EventType>>): Array<EventType> => r.body)
    );
  }

}
