/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Company } from '../models/company';
import { createCompany } from '../fn/companies/create-company';
import { CreateCompany$Params } from '../fn/companies/create-company';
import { deleteCompany } from '../fn/companies/delete-company';
import { DeleteCompany$Params } from '../fn/companies/delete-company';
import { getCompany } from '../fn/companies/get-company';
import { GetCompany$Params } from '../fn/companies/get-company';
import { listCompanies } from '../fn/companies/list-companies';
import { ListCompanies$Params } from '../fn/companies/list-companies';
import { updateCompany } from '../fn/companies/update-company';
import { UpdateCompany$Params } from '../fn/companies/update-company';


/**
 * Firmen
 */
@Injectable({ providedIn: 'root' })
export class CompaniesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listCompanies()` */
  static readonly ListCompaniesPath = '/api/v1/companies';

  /**
   * Alle Firmen mit Anzahl Bewerbungen.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listCompanies()` instead.
   *
   * This method doesn't expect any request body.
   */
  listCompanies$Response(params?: ListCompanies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Company>>> {
    const obs = listCompanies(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Alle Firmen mit Anzahl Bewerbungen.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listCompanies$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listCompanies(params?: ListCompanies$Params, context?: HttpContext): Observable<Array<Company>> {
    const resp = this.listCompanies$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<Company>>): Array<Company> => r.body)
    );
  }

  /** Path part for operation `createCompany()` */
  static readonly CreateCompanyPath = '/api/v1/companies';

  /**
   * Firma anlegen.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCompany()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCompany$Response(params: CreateCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<Company>> {
    const obs = createCompany(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Firma anlegen.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCompany$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCompany(params: CreateCompany$Params, context?: HttpContext): Observable<Company> {
    const resp = this.createCompany$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Company>): Company => r.body)
    );
  }

  /** Path part for operation `getCompany()` */
  static readonly GetCompanyPath = '/api/v1/companies/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCompany()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCompany$Response(params: GetCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<Company>> {
    const obs = getCompany(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCompany$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCompany(params: GetCompany$Params, context?: HttpContext): Observable<Company> {
    const resp = this.getCompany$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Company>): Company => r.body)
    );
  }

  /** Path part for operation `deleteCompany()` */
  static readonly DeleteCompanyPath = '/api/v1/companies/{id}';

  /**
   * Firma löschen (nur ohne Bewerbungen, sonst 409).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCompany()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCompany$Response(params: DeleteCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteCompany(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Firma löschen (nur ohne Bewerbungen, sonst 409).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCompany$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCompany(params: DeleteCompany$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteCompany$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateCompany()` */
  static readonly UpdateCompanyPath = '/api/v1/companies/{id}';

  /**
   * Firma ändern (nur gesetzte Felder; "" löscht optionale Felder).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCompany()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCompany$Response(params: UpdateCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<Company>> {
    const obs = updateCompany(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Firma ändern (nur gesetzte Felder; "" löscht optionale Felder).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCompany$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCompany(params: UpdateCompany$Params, context?: HttpContext): Observable<Company> {
    const resp = this.updateCompany$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Company>): Company => r.body)
    );
  }

}
