/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Cv } from '../models/cv';
import { getCv } from '../fn/cv/get-cv';
import { GetCv$Params } from '../fn/cv/get-cv';
import { saveCv } from '../fn/cv/save-cv';
import { SaveCv$Params } from '../fn/cv/save-cv';


/**
 * Lebenslauf
 */
@Injectable({ providedIn: 'root' })
export class CvService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCv()` */
  static readonly GetCvPath = '/api/v1/cv';

  /**
   * Lebenslauf lesen (leere Struktur, solange keiner gespeichert ist).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCv()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCv$Response(params?: GetCv$Params, context?: HttpContext): Observable<StrictHttpResponse<Cv>> {
    const obs = getCv(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Lebenslauf lesen (leere Struktur, solange keiner gespeichert ist).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCv(params?: GetCv$Params, context?: HttpContext): Observable<Cv> {
    const resp = this.getCv$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Cv>): Cv => r.body)
    );
  }

  /** Path part for operation `saveCv()` */
  static readonly SaveCvPath = '/api/v1/cv';

  /**
   * Lebenslauf ersetzen.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveCv()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveCv$Response(params: SaveCv$Params, context?: HttpContext): Observable<StrictHttpResponse<Cv>> {
    const obs = saveCv(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Lebenslauf ersetzen.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveCv$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveCv(params: SaveCv$Params, context?: HttpContext): Observable<Cv> {
    const resp = this.saveCv$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Cv>): Cv => r.body)
    );
  }

}
