/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Appointment } from '../models/appointment';
import { Deadline } from '../models/deadline';
import { FunnelStep } from '../models/funnel-step';
import { getFunnel } from '../fn/dashboard/get-funnel';
import { GetFunnel$Params } from '../fn/dashboard/get-funnel';
import { getSummary } from '../fn/dashboard/get-summary';
import { GetSummary$Params } from '../fn/dashboard/get-summary';
import { listAppointments } from '../fn/dashboard/list-appointments';
import { ListAppointments$Params } from '../fn/dashboard/list-appointments';
import { listDeadlines } from '../fn/dashboard/list-deadlines';
import { ListDeadlines$Params } from '../fn/dashboard/list-deadlines';
import { Summary } from '../models/summary';


/**
 * Übersicht: Fristen, Termine, Statistik
 */
@Injectable({ providedIn: 'root' })
export class DashboardService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listDeadlines()` */
  static readonly ListDeadlinesPath = '/api/v1/deadlines';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listDeadlines()` instead.
   *
   * This method doesn't expect any request body.
   */
  listDeadlines$Response(params?: ListDeadlines$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Deadline>>> {
    const obs = listDeadlines(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listDeadlines$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listDeadlines(params?: ListDeadlines$Params, context?: HttpContext): Observable<Array<Deadline>> {
    const resp = this.listDeadlines$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<Deadline>>): Array<Deadline> => r.body)
    );
  }

  /** Path part for operation `listAppointments()` */
  static readonly ListAppointmentsPath = '/api/v1/appointments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAppointments()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAppointments$Response(params?: ListAppointments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Appointment>>> {
    const obs = listAppointments(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAppointments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAppointments(params?: ListAppointments$Params, context?: HttpContext): Observable<Array<Appointment>> {
    const resp = this.listAppointments$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<Appointment>>): Array<Appointment> => r.body)
    );
  }

  /** Path part for operation `getFunnel()` */
  static readonly GetFunnelPath = '/api/v1/stats/funnel';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFunnel()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFunnel$Response(params?: GetFunnel$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FunnelStep>>> {
    const obs = getFunnel(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFunnel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFunnel(params?: GetFunnel$Params, context?: HttpContext): Observable<Array<FunnelStep>> {
    const resp = this.getFunnel$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<FunnelStep>>): Array<FunnelStep> => r.body)
    );
  }

  /** Path part for operation `getSummary()` */
  static readonly GetSummaryPath = '/api/v1/stats/summary';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSummary$Response(params?: GetSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<Summary>> {
    const obs = getSummary(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSummary(params?: GetSummary$Params, context?: HttpContext): Observable<Summary> {
    const resp = this.getSummary$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Summary>): Summary => r.body)
    );
  }

}
