/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Application } from '../models/application';
import { createDraft } from '../fn/documents/create-draft';
import { CreateDraft$Params } from '../fn/documents/create-draft';
import { Documents } from '../models/documents';
import { getDocuments } from '../fn/documents/get-documents';
import { GetDocuments$Params } from '../fn/documents/get-documents';
import { getDocumentsPdf } from '../fn/documents/get-documents-pdf';
import { GetDocumentsPdf$Params } from '../fn/documents/get-documents-pdf';
import { requestDocuments } from '../fn/documents/request-documents';
import { RequestDocuments$Params } from '../fn/documents/request-documents';
import { updateDocuments } from '../fn/documents/update-documents';
import { UpdateDocuments$Params } from '../fn/documents/update-documents';


/**
 * Bewerbungsunterlagen: Anschreiben + Lebenslauf als PDF, Gmail-Entwurf
 */
@Injectable({ providedIn: 'root' })
export class DocumentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `requestDocuments()` */
  static readonly RequestDocumentsPath = '/api/v1/applications/{id}/documents/request';

  /**
   * Unterlagen beim Agenten anfordern (auch erneut, z. B. nach einem Fehler).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `requestDocuments()` instead.
   *
   * This method doesn't expect any request body.
   */
  requestDocuments$Response(params: RequestDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Application>> {
    const obs = requestDocuments(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Unterlagen beim Agenten anfordern (auch erneut, z. B. nach einem Fehler).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `requestDocuments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  requestDocuments(params: RequestDocuments$Params, context?: HttpContext): Observable<Application> {
    const resp = this.requestDocuments$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Application>): Application => r.body)
    );
  }

  /** Path part for operation `getDocuments()` */
  static readonly GetDocumentsPath = '/api/v1/applications/{id}/documents';

  /**
   * Aktuelle Fassung der Unterlagen (404, solange keine erstellt sind).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDocuments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocuments$Response(params: GetDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Documents>> {
    const obs = getDocuments(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Aktuelle Fassung der Unterlagen (404, solange keine erstellt sind).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDocuments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocuments(params: GetDocuments$Params, context?: HttpContext): Observable<Documents> {
    const resp = this.getDocuments$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Documents>): Documents => r.body)
    );
  }

  /** Path part for operation `updateDocuments()` */
  static readonly UpdateDocumentsPath = '/api/v1/applications/{id}/documents';

  /**
   * Unterlagen bearbeiten (neue Version, neu gerendert; legt keinen Entwurf an).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateDocuments()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDocuments$Response(params: UpdateDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Documents>> {
    const obs = updateDocuments(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Unterlagen bearbeiten (neue Version, neu gerendert; legt keinen Entwurf an).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateDocuments$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDocuments(params: UpdateDocuments$Params, context?: HttpContext): Observable<Documents> {
    const resp = this.updateDocuments$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Documents>): Documents => r.body)
    );
  }

  /** Path part for operation `getDocumentsPdf()` */
  static readonly GetDocumentsPdfPath = '/api/v1/applications/{id}/documents/pdf';

  /**
   * Anschreiben + Lebenslauf als ein PDF (404 ohne Unterlagen).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDocumentsPdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocumentsPdf$Response(params: GetDocumentsPdf$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    const obs = getDocumentsPdf(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Anschreiben + Lebenslauf als ein PDF (404 ohne Unterlagen).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDocumentsPdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocumentsPdf(params: GetDocumentsPdf$Params, context?: HttpContext): Observable<Blob> {
    const resp = this.getDocumentsPdf$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `createDraft()` */
  static readonly CreateDraftPath = '/api/v1/applications/{id}/documents/draft';

  /**
   * Gmail-Entwurf (neu) anlegen.
   *
   * 400 ohne Bewerbungsadresse, 503 wenn Gmail nicht eingerichtet oder nicht erreichbar ist, 409 bei abgelehnter Anmeldung (App-Passwort prüfen).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createDraft()` instead.
   *
   * This method doesn't expect any request body.
   */
  createDraft$Response(params: CreateDraft$Params, context?: HttpContext): Observable<StrictHttpResponse<Application>> {
    const obs = createDraft(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Gmail-Entwurf (neu) anlegen.
   *
   * 400 ohne Bewerbungsadresse, 503 wenn Gmail nicht eingerichtet oder nicht erreichbar ist, 409 bei abgelehnter Anmeldung (App-Passwort prüfen).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createDraft$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createDraft(params: CreateDraft$Params, context?: HttpContext): Observable<Application> {
    const resp = this.createDraft$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Application>): Application => r.body)
    );
  }

}
