/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { acceptSuggestion } from '../fn/suggestions/accept-suggestion';
import { AcceptSuggestion$Params } from '../fn/suggestions/accept-suggestion';
import { Application } from '../models/application';
import { dismissSuggestion } from '../fn/suggestions/dismiss-suggestion';
import { DismissSuggestion$Params } from '../fn/suggestions/dismiss-suggestion';
import { listSuggestions } from '../fn/suggestions/list-suggestions';
import { ListSuggestions$Params } from '../fn/suggestions/list-suggestions';
import { Suggestion } from '../models/suggestion';


/**
 * Vorschläge des Agenten aus der Postfach-Auswertung
 */
@Injectable({ providedIn: 'root' })
export class SuggestionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listSuggestions()` */
  static readonly ListSuggestionsPath = '/api/v1/suggestions';

  /**
   * Offene Vorschläge des Agenten, älteste zuerst.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listSuggestions()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSuggestions$Response(params?: ListSuggestions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Suggestion>>> {
    const obs = listSuggestions(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Offene Vorschläge des Agenten, älteste zuerst.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listSuggestions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSuggestions(params?: ListSuggestions$Params, context?: HttpContext): Observable<Array<Suggestion>> {
    const resp = this.listSuggestions$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<Suggestion>>): Array<Suggestion> => r.body)
    );
  }

  /** Path part for operation `acceptSuggestion()` */
  static readonly AcceptSuggestionPath = '/api/v1/suggestions/{id}/accept';

  /**
   * Vorschlag übernehmen (legt das Ereignis an).
   *
   * Bei nicht zugeordneten Vorschlägen ist `application_id` Pflicht (sonst 400). 422 bei unerlaubtem Übergang, 409, wenn der Vorschlag schon entschieden ist.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `acceptSuggestion()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  acceptSuggestion$Response(params: AcceptSuggestion$Params, context?: HttpContext): Observable<StrictHttpResponse<Application>> {
    const obs = acceptSuggestion(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Vorschlag übernehmen (legt das Ereignis an).
   *
   * Bei nicht zugeordneten Vorschlägen ist `application_id` Pflicht (sonst 400). 422 bei unerlaubtem Übergang, 409, wenn der Vorschlag schon entschieden ist.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `acceptSuggestion$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  acceptSuggestion(params: AcceptSuggestion$Params, context?: HttpContext): Observable<Application> {
    const resp = this.acceptSuggestion$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Application>): Application => r.body)
    );
  }

  /** Path part for operation `dismissSuggestion()` */
  static readonly DismissSuggestionPath = '/api/v1/suggestions/{id}/dismiss';

  /**
   * Vorschlag verwerfen (409, wenn schon entschieden).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dismissSuggestion()` instead.
   *
   * This method doesn't expect any request body.
   */
  dismissSuggestion$Response(params: DismissSuggestion$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = dismissSuggestion(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Vorschlag verwerfen (409, wenn schon entschieden).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dismissSuggestion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dismissSuggestion(params: DismissSuggestion$Params, context?: HttpContext): Observable<void> {
    const resp = this.dismissSuggestion$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
