// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: applications.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (company_id, position_title, job_url, location, source, notes, current_status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, position_title, job_url, location, source, notes, current_status, created_at, updated_at
`

type CreateApplicationParams struct {
	CompanyID     uuid.UUID
	PositionTitle string
	JobUrl        *string
	Location      *string
	Source        *string
	Notes         *string
	CurrentStatus string
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.CompanyID,
		arg.PositionTitle,
		arg.JobUrl,
		arg.Location,
		arg.Source,
		arg.Notes,
		arg.CurrentStatus,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PositionTitle,
		&i.JobUrl,
		&i.Location,
		&i.Source,
		&i.Notes,
		&i.CurrentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :execrows
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplication, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplication = `-- name: GetApplication :one
SELECT a.id, a.company_id, c.name AS company_name, a.position_title, a.job_url, a.location,
       a.source, a.notes, a.current_status, a.created_at, a.updated_at
FROM applications a
JOIN companies c ON c.id = a.company_id
WHERE a.id = $1
`

type GetApplicationRow struct {
	ID            uuid.UUID
	CompanyID     uuid.UUID
	CompanyName   string
	PositionTitle string
	JobUrl        *string
	Location      *string
	Source        *string
	Notes         *string
	CurrentStatus string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (GetApplicationRow, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i GetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CompanyName,
		&i.PositionTitle,
		&i.JobUrl,
		&i.Location,
		&i.Source,
		&i.Notes,
		&i.CurrentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT a.id, a.company_id, c.name AS company_name, a.position_title, a.current_status,
       a.updated_at, le.occurred_on AS last_event_on, le.due_on AS open_due_on
FROM applications a
JOIN companies c ON c.id = a.company_id
JOIN latest_events le ON le.application_id = a.id
WHERE ($1::text[] IS NULL OR a.current_status = ANY ($1::text[]))
  AND ($2::text IS NULL
       OR strpos(lower(c.name), lower($2::text)) > 0
       OR strpos(lower(a.position_title), lower($2::text)) > 0)
ORDER BY a.updated_at DESC, a.id
`

type ListApplicationsParams struct {
	Statuses []string
	Query    *string
}

type ListApplicationsRow struct {
	ID            uuid.UUID
	CompanyID     uuid.UUID
	CompanyName   string
	PositionTitle string
	CurrentStatus string
	UpdatedAt     time.Time
	LastEventOn   time.Time
	OpenDueOn     *time.Time
}

func (q *Queries) ListApplications(ctx context.Context, arg ListApplicationsParams) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications, arg.Statuses, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsRow
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CompanyName,
			&i.PositionTitle,
			&i.CurrentStatus,
			&i.UpdatedAt,
			&i.LastEventOn,
			&i.OpenDueOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockApplication = `-- name: LockApplication :one
SELECT id, company_id, position_title, job_url, location, source, notes, current_status, created_at, updated_at FROM applications WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockApplication(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, lockApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PositionTitle,
		&i.JobUrl,
		&i.Location,
		&i.Source,
		&i.Notes,
		&i.CurrentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setApplicationStatus = `-- name: SetApplicationStatus :exec
UPDATE applications SET current_status = $2, updated_at = now() WHERE id = $1
`

type SetApplicationStatusParams struct {
	ID            uuid.UUID
	CurrentStatus string
}

func (q *Queries) SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) error {
	_, err := q.db.Exec(ctx, setApplicationStatus, arg.ID, arg.CurrentStatus)
	return err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET company_id = $2, position_title = $3, job_url = $4, location = $5, source = $6, notes = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, company_id, position_title, job_url, location, source, notes, current_status, created_at, updated_at
`

type UpdateApplicationParams struct {
	ID            uuid.UUID
	CompanyID     uuid.UUID
	PositionTitle string
	JobUrl        *string
	Location      *string
	Source        *string
	Notes         *string
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.CompanyID,
		arg.PositionTitle,
		arg.JobUrl,
		arg.Location,
		arg.Source,
		arg.Notes,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PositionTitle,
		&i.JobUrl,
		&i.Location,
		&i.Source,
		&i.Notes,
		&i.CurrentStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
