// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: companies.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, website, notes)
VALUES ($1, $2, $3)
RETURNING id, name, website, notes, created_at
`

type CreateCompanyParams struct {
	Name    string
	Website *string
	Notes   *string
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany, arg.Name, arg.Website, arg.Notes)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :execrows
DELETE FROM companies WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompany, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompany = `-- name: GetCompany :one
SELECT c.id, c.name, c.website, c.notes, c.created_at,
       count(a.id)::int AS application_count
FROM companies c
LEFT JOIN applications a ON a.company_id = c.id
WHERE c.id = $1
GROUP BY c.id
`

type GetCompanyRow struct {
	ID               uuid.UUID
	Name             string
	Website          *string
	Notes            *string
	CreatedAt        time.Time
	ApplicationCount int32
}

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (GetCompanyRow, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i GetCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.Notes,
		&i.CreatedAt,
		&i.ApplicationCount,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT c.id, c.name, c.website, c.notes, c.created_at,
       count(a.id)::int AS application_count
FROM companies c
LEFT JOIN applications a ON a.company_id = c.id
GROUP BY c.id
ORDER BY lower(c.name)
`

type ListCompaniesRow struct {
	ID               uuid.UUID
	Name             string
	Website          *string
	Notes            *string
	CreatedAt        time.Time
	ApplicationCount int32
}

func (q *Queries) ListCompanies(ctx context.Context) ([]ListCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesRow
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Website,
			&i.Notes,
			&i.CreatedAt,
			&i.ApplicationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = $2, website = $3, notes = $4
WHERE id = $1
RETURNING id, name, website, notes, created_at
`

type UpdateCompanyParams struct {
	ID      uuid.UUID
	Name    string
	Website *string
	Notes   *string
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Website,
		arg.Notes,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Website,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
