// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cv.sql

package store

import (
	"context"
	"time"
)

const getCV = `-- name: GetCV :one
SELECT data, updated_at FROM cv WHERE id = 1
`

type GetCVRow struct {
	Data      []byte
	UpdatedAt time.Time
}

func (q *Queries) GetCV(ctx context.Context) (GetCVRow, error) {
	row := q.db.QueryRow(ctx, getCV)
	var i GetCVRow
	err := row.Scan(&i.Data, &i.UpdatedAt)
	return i, err
}

const upsertCV = `-- name: UpsertCV :one
INSERT INTO cv (id, data, updated_at)
VALUES (1, $1, now())
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, updated_at = now()
RETURNING data, updated_at
`

type UpsertCVRow struct {
	Data      []byte
	UpdatedAt time.Time
}

func (q *Queries) UpsertCV(ctx context.Context, data []byte) (UpsertCVRow, error) {
	row := q.db.QueryRow(ctx, upsertCV, data)
	var i UpsertCVRow
	err := row.Scan(&i.Data, &i.UpdatedAt)
	return i, err
}
