// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cv_photo.sql

package store

import (
	"context"
	"time"
)

const deleteCVPhoto = `-- name: DeleteCVPhoto :exec
DELETE FROM cv_photo WHERE id = 1
`

func (q *Queries) DeleteCVPhoto(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteCVPhoto)
	return err
}

const getCVPhoto = `-- name: GetCVPhoto :one
SELECT image, updated_at FROM cv_photo WHERE id = 1
`

type GetCVPhotoRow struct {
	Image     []byte
	UpdatedAt time.Time
}

func (q *Queries) GetCVPhoto(ctx context.Context) (GetCVPhotoRow, error) {
	row := q.db.QueryRow(ctx, getCVPhoto)
	var i GetCVPhotoRow
	err := row.Scan(&i.Image, &i.UpdatedAt)
	return i, err
}

const upsertCVPhoto = `-- name: UpsertCVPhoto :exec
INSERT INTO cv_photo (id, image, updated_at)
VALUES (1, $1, now())
ON CONFLICT (id) DO UPDATE SET image = EXCLUDED.image, updated_at = now()
`

func (q *Queries) UpsertCVPhoto(ctx context.Context, image []byte) error {
	_, err := q.db.Exec(ctx, upsertCVPhoto, image)
	return err
}
