// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cv_reviews.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeOpenCVReviews = `-- name: CloseOpenCVReviews :exec
UPDATE cv_reviews
SET state = 'abgeschlossen', completed_at = coalesce(completed_at, now())
WHERE state IN ('angefordert', 'fertig')
`

func (q *Queries) CloseOpenCVReviews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, closeOpenCVReviews)
	return err
}

const completeCVReview = `-- name: CompleteCVReview :one
UPDATE cv_reviews
SET state = 'fertig', proposal = $2, notes = $3, completed_at = now()
WHERE id = $1 AND state = 'angefordert'
RETURNING id, state, based_on_updated_at, proposal, notes, requested_at, completed_at
`

type CompleteCVReviewParams struct {
	ID       uuid.UUID
	Proposal []byte
	Notes    []byte
}

func (q *Queries) CompleteCVReview(ctx context.Context, arg CompleteCVReviewParams) (CvReview, error) {
	row := q.db.QueryRow(ctx, completeCVReview, arg.ID, arg.Proposal, arg.Notes)
	var i CvReview
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.BasedOnUpdatedAt,
		&i.Proposal,
		&i.Notes,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createCVReview = `-- name: CreateCVReview :one
INSERT INTO cv_reviews (state, based_on_updated_at)
VALUES ('angefordert', $1)
RETURNING id, state, based_on_updated_at, proposal, notes, requested_at, completed_at
`

func (q *Queries) CreateCVReview(ctx context.Context, basedOnUpdatedAt time.Time) (CvReview, error) {
	row := q.db.QueryRow(ctx, createCVReview, basedOnUpdatedAt)
	var i CvReview
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.BasedOnUpdatedAt,
		&i.Proposal,
		&i.Notes,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCVReview = `-- name: GetCVReview :one
SELECT id, state, based_on_updated_at, proposal, notes, requested_at, completed_at FROM cv_reviews WHERE id = $1
`

func (q *Queries) GetCVReview(ctx context.Context, id uuid.UUID) (CvReview, error) {
	row := q.db.QueryRow(ctx, getCVReview, id)
	var i CvReview
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.BasedOnUpdatedAt,
		&i.Proposal,
		&i.Notes,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOpenCVReview = `-- name: GetOpenCVReview :one
SELECT id, state, based_on_updated_at, proposal, notes, requested_at, completed_at FROM cv_reviews WHERE state IN ('angefordert', 'fertig')
`

func (q *Queries) GetOpenCVReview(ctx context.Context) (CvReview, error) {
	row := q.db.QueryRow(ctx, getOpenCVReview)
	var i CvReview
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.BasedOnUpdatedAt,
		&i.Proposal,
		&i.Notes,
		&i.RequestedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCVReviewsByState = `-- name: ListCVReviewsByState :many
SELECT id, state, based_on_updated_at, proposal, notes, requested_at, completed_at FROM cv_reviews WHERE state = $1 ORDER BY requested_at
`

func (q *Queries) ListCVReviewsByState(ctx context.Context, state string) ([]CvReview, error) {
	rows, err := q.db.Query(ctx, listCVReviewsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CvReview
	for rows.Next() {
		var i CvReview
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.BasedOnUpdatedAt,
			&i.Proposal,
			&i.Notes,
			&i.RequestedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
