// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listAllEventsWithSource = `-- name: ListAllEventsWithSource :many
SELECT e.application_id, a.source, e.type, e.occurred_on, e.created_at
FROM application_events e
JOIN applications a ON a.id = e.application_id
ORDER BY e.application_id, e.created_at, e.id
`

type ListAllEventsWithSourceRow struct {
	ApplicationID uuid.UUID
	Source        *string
	Type          string
	OccurredOn    time.Time
	CreatedAt     time.Time
}

func (q *Queries) ListAllEventsWithSource(ctx context.Context) ([]ListAllEventsWithSourceRow, error) {
	rows, err := q.db.Query(ctx, listAllEventsWithSource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllEventsWithSourceRow
	for rows.Next() {
		var i ListAllEventsWithSourceRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.Source,
			&i.Type,
			&i.OccurredOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenDeadlines = `-- name: ListOpenDeadlines :many
SELECT a.id AS application_id, c.name AS company_name, a.position_title,
       le.type AS event_type, le.due_on
FROM latest_events le
JOIN applications a ON a.id = le.application_id
JOIN companies c ON c.id = a.company_id
WHERE le.due_on IS NOT NULL
  AND le.due_on <= $1::date
ORDER BY le.due_on, c.name, a.id
`

type ListOpenDeadlinesRow struct {
	ApplicationID uuid.UUID
	CompanyName   string
	PositionTitle string
	EventType     string
	DueOn         *time.Time
}

func (q *Queries) ListOpenDeadlines(ctx context.Context, untilDate time.Time) ([]ListOpenDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, listOpenDeadlines, untilDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenDeadlinesRow
	for rows.Next() {
		var i ListOpenDeadlinesRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.CompanyName,
			&i.PositionTitle,
			&i.EventType,
			&i.DueOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingAppointments = `-- name: ListUpcomingAppointments :many
SELECT a.id AS application_id, c.name AS company_name, a.position_title,
       le.type AS event_type, le.occurred_on, le.interview_round
FROM latest_events le
JOIN applications a ON a.id = le.application_id
JOIN companies c ON c.id = a.company_id
WHERE le.type IN ('ScreeningGespraech', 'Interview', 'Kennenlerntag')
  AND le.occurred_on BETWEEN $1::date AND $2::date
ORDER BY le.occurred_on, c.name, a.id
`

type ListUpcomingAppointmentsParams struct {
	FromDate  time.Time
	UntilDate time.Time
}

type ListUpcomingAppointmentsRow struct {
	ApplicationID  uuid.UUID
	CompanyName    string
	PositionTitle  string
	EventType      string
	OccurredOn     time.Time
	InterviewRound *int32
}

func (q *Queries) ListUpcomingAppointments(ctx context.Context, arg ListUpcomingAppointmentsParams) ([]ListUpcomingAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingAppointments, arg.FromDate, arg.UntilDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingAppointmentsRow
	for rows.Next() {
		var i ListUpcomingAppointmentsRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.CompanyName,
			&i.PositionTitle,
			&i.EventType,
			&i.OccurredOn,
			&i.InterviewRound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
