// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getDocuments = `-- name: GetDocuments :one
SELECT application_id, version, language, cover_letter, profile_line, highlights, mail_subject, mail_body, pdf, file_name, rendered_at, updated_at FROM application_documents WHERE application_id = $1
`

func (q *Queries) GetDocuments(ctx context.Context, applicationID uuid.UUID) (ApplicationDocument, error) {
	row := q.db.QueryRow(ctx, getDocuments, applicationID)
	var i ApplicationDocument
	err := row.Scan(
		&i.ApplicationID,
		&i.Version,
		&i.Language,
		&i.CoverLetter,
		&i.ProfileLine,
		&i.Highlights,
		&i.MailSubject,
		&i.MailBody,
		&i.Pdf,
		&i.FileName,
		&i.RenderedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentApplicationsByDocumentsState = `-- name: ListAgentApplicationsByDocumentsState :many
SELECT a.id, c.name AS company_name, c.website AS company_website, a.position_title, a.job_url, a.location,
       a.contact_email, a.posting_text, a.fit_reason, a.documents_state,
       COALESCE(d.version, 0)::int AS documents_version
FROM applications a
JOIN companies c ON c.id = a.company_id
LEFT JOIN application_documents d ON d.application_id = a.id
WHERE a.documents_state = $1
ORDER BY a.updated_at, a.id
`

type ListAgentApplicationsByDocumentsStateRow struct {
	ID               uuid.UUID
	CompanyName      string
	CompanyWebsite   *string
	PositionTitle    string
	JobUrl           *string
	Location         *string
	ContactEmail     *string
	PostingText      *string
	FitReason        *string
	DocumentsState   string
	DocumentsVersion int32
}

func (q *Queries) ListAgentApplicationsByDocumentsState(ctx context.Context, documentsState string) ([]ListAgentApplicationsByDocumentsStateRow, error) {
	rows, err := q.db.Query(ctx, listAgentApplicationsByDocumentsState, documentsState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentApplicationsByDocumentsStateRow
	for rows.Next() {
		var i ListAgentApplicationsByDocumentsStateRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.CompanyWebsite,
			&i.PositionTitle,
			&i.JobUrl,
			&i.Location,
			&i.ContactEmail,
			&i.PostingText,
			&i.FitReason,
			&i.DocumentsState,
			&i.DocumentsVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentsState = `-- name: SetDocumentsState :exec
UPDATE applications SET documents_state = $2, documents_error = $3, updated_at = now() WHERE id = $1
`

type SetDocumentsStateParams struct {
	ID             uuid.UUID
	DocumentsState string
	DocumentsError *string
}

func (q *Queries) SetDocumentsState(ctx context.Context, arg SetDocumentsStateParams) error {
	_, err := q.db.Exec(ctx, setDocumentsState, arg.ID, arg.DocumentsState, arg.DocumentsError)
	return err
}

const setDraftCreated = `-- name: SetDraftCreated :exec
UPDATE applications SET documents_state = 'entwurf_angelegt', documents_error = NULL, gmail_draft_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SetDraftCreated(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setDraftCreated, id)
	return err
}

const upsertDocuments = `-- name: UpsertDocuments :one
INSERT INTO application_documents (application_id, version, language, cover_letter, profile_line, highlights,
                                   mail_subject, mail_body, pdf, file_name, rendered_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
ON CONFLICT (application_id) DO UPDATE
SET version = EXCLUDED.version, language = EXCLUDED.language, cover_letter = EXCLUDED.cover_letter,
    profile_line = EXCLUDED.profile_line, highlights = EXCLUDED.highlights, mail_subject = EXCLUDED.mail_subject,
    mail_body = EXCLUDED.mail_body, pdf = EXCLUDED.pdf, file_name = EXCLUDED.file_name,
    rendered_at = EXCLUDED.rendered_at, updated_at = now()
RETURNING application_id, version, language, cover_letter, profile_line, highlights, mail_subject, mail_body, pdf, file_name, rendered_at, updated_at
`

type UpsertDocumentsParams struct {
	ApplicationID uuid.UUID
	Version       int32
	Language      string
	CoverLetter   string
	ProfileLine   *string
	Highlights    []byte
	MailSubject   string
	MailBody      string
	Pdf           []byte
	FileName      *string
	RenderedAt    *time.Time
}

func (q *Queries) UpsertDocuments(ctx context.Context, arg UpsertDocumentsParams) (ApplicationDocument, error) {
	row := q.db.QueryRow(ctx, upsertDocuments,
		arg.ApplicationID,
		arg.Version,
		arg.Language,
		arg.CoverLetter,
		arg.ProfileLine,
		arg.Highlights,
		arg.MailSubject,
		arg.MailBody,
		arg.Pdf,
		arg.FileName,
		arg.RenderedAt,
	)
	var i ApplicationDocument
	err := row.Scan(
		&i.ApplicationID,
		&i.Version,
		&i.Language,
		&i.CoverLetter,
		&i.ProfileLine,
		&i.Highlights,
		&i.MailSubject,
		&i.MailBody,
		&i.Pdf,
		&i.FileName,
		&i.RenderedAt,
		&i.UpdatedAt,
	)
	return i, err
}
