// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM application_events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO application_events (application_id, type, occurred_on, due_on, interview_round, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, application_id, type, occurred_on, due_on, interview_round, note, created_at
`

type InsertEventParams struct {
	ApplicationID  uuid.UUID
	Type           string
	OccurredOn     time.Time
	DueOn          *time.Time
	InterviewRound *int32
	Note           *string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (ApplicationEvent, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ApplicationID,
		arg.Type,
		arg.OccurredOn,
		arg.DueOn,
		arg.InterviewRound,
		arg.Note,
	)
	var i ApplicationEvent
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Type,
		&i.OccurredOn,
		&i.DueOn,
		&i.InterviewRound,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, application_id, type, occurred_on, due_on, interview_round, note, created_at FROM application_events
WHERE application_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListEvents(ctx context.Context, applicationID uuid.UUID) ([]ApplicationEvent, error) {
	rows, err := q.db.Query(ctx, listEvents, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationEvent
	for rows.Next() {
		var i ApplicationEvent
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Type,
			&i.OccurredOn,
			&i.DueOn,
			&i.InterviewRound,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
