// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mailbox.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const decideSuggestion = `-- name: DecideSuggestion :exec
UPDATE status_suggestions
SET state = $1, decided_at = now(),
    application_id = COALESCE($2, application_id)
WHERE id = $3
`

type DecideSuggestionParams struct {
	State         string
	ApplicationID *uuid.UUID
	ID            uuid.UUID
}

// Setzt die Entscheidung; application_id bleibt unverändert, wenn keine übergeben wird.
func (q *Queries) DecideSuggestion(ctx context.Context, arg DecideSuggestionParams) error {
	_, err := q.db.Exec(ctx, decideSuggestion, arg.State, arg.ApplicationID, arg.ID)
	return err
}

const getProcessedMail = `-- name: GetProcessedMail :one
SELECT gmail_message_id, application_id, outcome, processed_at FROM processed_mails WHERE gmail_message_id = $1
`

func (q *Queries) GetProcessedMail(ctx context.Context, gmailMessageID string) (ProcessedMail, error) {
	row := q.db.QueryRow(ctx, getProcessedMail, gmailMessageID)
	var i ProcessedMail
	err := row.Scan(
		&i.GmailMessageID,
		&i.ApplicationID,
		&i.Outcome,
		&i.ProcessedAt,
	)
	return i, err
}

const getSuggestion = `-- name: GetSuggestion :one
SELECT s.id, s.application_id, c.name AS company_name, a.position_title, s.suggested_type, s.occurred_on,
       s.due_on, s.reason, s.mail_subject, s.mail_from, s.mail_url, s.state, s.created_at, s.decided_at
FROM status_suggestions s
LEFT JOIN applications a ON a.id = s.application_id
LEFT JOIN companies c ON c.id = a.company_id
WHERE s.id = $1
`

type GetSuggestionRow struct {
	ID            uuid.UUID
	ApplicationID *uuid.UUID
	CompanyName   *string
	PositionTitle *string
	SuggestedType string
	OccurredOn    time.Time
	DueOn         *time.Time
	Reason        string
	MailSubject   *string
	MailFrom      *string
	MailUrl       *string
	State         string
	CreatedAt     time.Time
	DecidedAt     *time.Time
}

func (q *Queries) GetSuggestion(ctx context.Context, id uuid.UUID) (GetSuggestionRow, error) {
	row := q.db.QueryRow(ctx, getSuggestion, id)
	var i GetSuggestionRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.CompanyName,
		&i.PositionTitle,
		&i.SuggestedType,
		&i.OccurredOn,
		&i.DueOn,
		&i.Reason,
		&i.MailSubject,
		&i.MailFrom,
		&i.MailUrl,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertProcessedMail = `-- name: InsertProcessedMail :one
INSERT INTO processed_mails (gmail_message_id, application_id, outcome)
VALUES ($1, $2, $3)
ON CONFLICT (gmail_message_id) DO NOTHING
RETURNING gmail_message_id, application_id, outcome, processed_at
`

type InsertProcessedMailParams struct {
	GmailMessageID string
	ApplicationID  *uuid.UUID
	Outcome        string
}

func (q *Queries) InsertProcessedMail(ctx context.Context, arg InsertProcessedMailParams) (ProcessedMail, error) {
	row := q.db.QueryRow(ctx, insertProcessedMail, arg.GmailMessageID, arg.ApplicationID, arg.Outcome)
	var i ProcessedMail
	err := row.Scan(
		&i.GmailMessageID,
		&i.ApplicationID,
		&i.Outcome,
		&i.ProcessedAt,
	)
	return i, err
}

const insertSuggestion = `-- name: InsertSuggestion :one
INSERT INTO status_suggestions (application_id, suggested_type, occurred_on, due_on, reason,
                                mail_subject, mail_from, mail_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, application_id, suggested_type, occurred_on, due_on, reason, mail_subject, mail_from, mail_url, state, created_at, decided_at
`

type InsertSuggestionParams struct {
	ApplicationID *uuid.UUID
	SuggestedType string
	OccurredOn    time.Time
	DueOn         *time.Time
	Reason        string
	MailSubject   *string
	MailFrom      *string
	MailUrl       *string
}

func (q *Queries) InsertSuggestion(ctx context.Context, arg InsertSuggestionParams) (StatusSuggestion, error) {
	row := q.db.QueryRow(ctx, insertSuggestion,
		arg.ApplicationID,
		arg.SuggestedType,
		arg.OccurredOn,
		arg.DueOn,
		arg.Reason,
		arg.MailSubject,
		arg.MailFrom,
		arg.MailUrl,
	)
	var i StatusSuggestion
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SuggestedType,
		&i.OccurredOn,
		&i.DueOn,
		&i.Reason,
		&i.MailSubject,
		&i.MailFrom,
		&i.MailUrl,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listOpenAgentApplications = `-- name: ListOpenAgentApplications :many
SELECT a.id, c.name AS company_name, c.website AS company_website, a.position_title, a.current_status,
       a.contact_email, a.gmail_thread_id, a.documents_state, a.gmail_draft_at, d.mail_subject, a.updated_at
FROM applications a
JOIN companies c ON c.id = a.company_id
LEFT JOIN application_documents d ON d.application_id = a.id
WHERE a.current_status = ANY ($1::text[])
ORDER BY lower(c.name), lower(a.position_title), a.id
`

type ListOpenAgentApplicationsRow struct {
	ID             uuid.UUID
	CompanyName    string
	CompanyWebsite *string
	PositionTitle  string
	CurrentStatus  string
	ContactEmail   *string
	GmailThreadID  *string
	DocumentsState string
	GmailDraftAt   *time.Time
	MailSubject    *string
	UpdatedAt      time.Time
}

// Laufende Bewerbungen für die Postfach-Auswertung; statuses = alle Status außerhalb der Phase Abgeschlossen.
func (q *Queries) ListOpenAgentApplications(ctx context.Context, statuses []string) ([]ListOpenAgentApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listOpenAgentApplications, statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenAgentApplicationsRow
	for rows.Next() {
		var i ListOpenAgentApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.CompanyWebsite,
			&i.PositionTitle,
			&i.CurrentStatus,
			&i.ContactEmail,
			&i.GmailThreadID,
			&i.DocumentsState,
			&i.GmailDraftAt,
			&i.MailSubject,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenSuggestions = `-- name: ListOpenSuggestions :many
SELECT s.id, s.application_id, c.name AS company_name, a.position_title, s.suggested_type, s.occurred_on,
       s.due_on, s.reason, s.mail_subject, s.mail_from, s.mail_url, s.state, s.created_at, s.decided_at
FROM status_suggestions s
LEFT JOIN applications a ON a.id = s.application_id
LEFT JOIN companies c ON c.id = a.company_id
WHERE s.state = 'offen'
ORDER BY s.created_at, s.id
`

type ListOpenSuggestionsRow struct {
	ID            uuid.UUID
	ApplicationID *uuid.UUID
	CompanyName   *string
	PositionTitle *string
	SuggestedType string
	OccurredOn    time.Time
	DueOn         *time.Time
	Reason        string
	MailSubject   *string
	MailFrom      *string
	MailUrl       *string
	State         string
	CreatedAt     time.Time
	DecidedAt     *time.Time
}

func (q *Queries) ListOpenSuggestions(ctx context.Context) ([]ListOpenSuggestionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenSuggestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenSuggestionsRow
	for rows.Next() {
		var i ListOpenSuggestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.CompanyName,
			&i.PositionTitle,
			&i.SuggestedType,
			&i.OccurredOn,
			&i.DueOn,
			&i.Reason,
			&i.MailSubject,
			&i.MailFrom,
			&i.MailUrl,
			&i.State,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSuggestion = `-- name: LockSuggestion :one
SELECT id, application_id, suggested_type, occurred_on, due_on, reason, mail_subject, mail_from, mail_url, state, created_at, decided_at FROM status_suggestions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSuggestion(ctx context.Context, id uuid.UUID) (StatusSuggestion, error) {
	row := q.db.QueryRow(ctx, lockSuggestion, id)
	var i StatusSuggestion
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SuggestedType,
		&i.OccurredOn,
		&i.DueOn,
		&i.Reason,
		&i.MailSubject,
		&i.MailFrom,
		&i.MailUrl,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const setGmailThread = `-- name: SetGmailThread :exec
UPDATE applications SET gmail_thread_id = $2, updated_at = now() WHERE id = $1
`

type SetGmailThreadParams struct {
	ID            uuid.UUID
	GmailThreadID *string
}

func (q *Queries) SetGmailThread(ctx context.Context, arg SetGmailThreadParams) error {
	_, err := q.db.Exec(ctx, setGmailThread, arg.ID, arg.GmailThreadID)
	return err
}
