// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type Application struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	PositionTitle  string
	JobUrl         *string
	Location       *string
	Source         *string
	Notes          *string
	CurrentStatus  string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ContactEmail   *string
	PostingText    *string
	FitScore       *int32
	FitReason      *string
	CreatedByAgent bool
}

type ApplicationEvent struct {
	ID             uuid.UUID
	ApplicationID  uuid.UUID
	Type           string
	OccurredOn     time.Time
	DueOn          *time.Time
	InterviewRound *int32
	Note           *string
	CreatedAt      time.Time
}

type Company struct {
	ID        uuid.UUID
	Name      string
	Website   *string
	Notes     *string
	CreatedAt time.Time
}

type Cv struct {
	ID        int32
	Data      []byte
	UpdatedAt time.Time
}

type CvPhoto struct {
	ID        int32
	Image     []byte
	UpdatedAt time.Time
}

type CvReview struct {
	ID               uuid.UUID
	State            string
	BasedOnUpdatedAt time.Time
	Proposal         []byte
	Notes            []byte
	RequestedAt      time.Time
	CompletedAt      *time.Time
}

type LatestEvent struct {
	ApplicationID  uuid.UUID
	EventID        uuid.UUID
	Type           string
	OccurredOn     time.Time
	DueOn          *time.Time
	InterviewRound *int32
}
