//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventType.
const (
	Absage             EventType = "Absage"
	AngebotAbgelehnt   EventType = "AngebotAbgelehnt"
	AngebotAngenommen  EventType = "AngebotAngenommen"
	AngebotErhalten    EventType = "AngebotErhalten"
	Beworben           EventType = "Beworben"
	ChallengeAbgegeben EventType = "ChallengeAbgegeben"
	ChallengeErhalten  EventType = "ChallengeErhalten"
	Interview          EventType = "Interview"
	KeineRueckmeldung  EventType = "KeineRueckmeldung"
	Kennenlerntag      EventType = "Kennenlerntag"
	ScreeningGespraech EventType = "ScreeningGespraech"
	Vorgemerkt         EventType = "Vorgemerkt"
	Zurueckgezogen     EventType = "Zurueckgezogen"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case Absage:
		return true
	case AngebotAbgelehnt:
		return true
	case AngebotAngenommen:
		return true
	case AngebotErhalten:
		return true
	case Beworben:
		return true
	case ChallengeAbgegeben:
		return true
	case ChallengeErhalten:
		return true
	case Interview:
		return true
	case KeineRueckmeldung:
		return true
	case Kennenlerntag:
		return true
	case ScreeningGespraech:
		return true
	case Vorgemerkt:
		return true
	case Zurueckgezogen:
		return true
	default:
		return false
	}
}

// Defines values for Phase.
const (
	Abgeschlossen Phase = "Abgeschlossen"
	Aktiv         Phase = "Aktiv"
	Vorbereitung  Phase = "Vorbereitung"
)

// Valid indicates whether the value is a known member of the Phase enum.
func (e Phase) Valid() bool {
	switch e {
	case Abgeschlossen:
		return true
	case Aktiv:
		return true
	case Vorbereitung:
		return true
	default:
		return false
	}
}

// Application defines model for Application.
type Application struct {
	CompanyId     openapi_types.UUID `json:"company_id"`
	CompanyName   string             `json:"company_name"`
	CreatedAt     time.Time          `json:"created_at"`
	Events        []Event            `json:"events"`
	Id            openapi_types.UUID `json:"id"`
	JobUrl        *string            `json:"job_url,omitempty"`
	Location      *string            `json:"location,omitempty"`
	Notes         *string            `json:"notes,omitempty"`
	Phase         Phase              `json:"phase"`
	PositionTitle string             `json:"position_title"`
	Source        *string            `json:"source,omitempty"`
	Status        EventType          `json:"status"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// ApplicationInput defines model for ApplicationInput.
type ApplicationInput struct {
	CompanyId     openapi_types.UUID `json:"company_id"`
	FirstEvent    NewEvent           `json:"first_event"`
	JobUrl        *string            `json:"job_url,omitempty"`
	Location      *string            `json:"location,omitempty"`
	Notes         *string            `json:"notes,omitempty"`
	PositionTitle string             `json:"position_title"`
	Source        *string            `json:"source,omitempty"`
}

// ApplicationPatch defines model for ApplicationPatch.
type ApplicationPatch struct {
	CompanyId     *openapi_types.UUID `json:"company_id,omitempty"`
	JobUrl        *string             `json:"job_url,omitempty"`
	Location      *string             `json:"location,omitempty"`
	Notes         *string             `json:"notes,omitempty"`
	PositionTitle *string             `json:"position_title,omitempty"`
	Source        *string             `json:"source,omitempty"`
}

// ApplicationSummary defines model for ApplicationSummary.
type ApplicationSummary struct {
	CompanyId     openapi_types.UUID  `json:"company_id"`
	CompanyName   string              `json:"company_name"`
	Id            openapi_types.UUID  `json:"id"`
	LastEventOn   openapi_types.Date  `json:"last_event_on"`
	OpenDueOn     *openapi_types.Date `json:"open_due_on,omitempty"`
	Phase         Phase               `json:"phase"`
	PositionTitle string              `json:"position_title"`
	Status        EventType           `json:"status"`
	UpdatedAt     time.Time           `json:"updated_at"`
}

// Appointment defines model for Appointment.
type Appointment struct {
	ApplicationId  openapi_types.UUID `json:"application_id"`
	CompanyName    string             `json:"company_name"`
	Date           openapi_types.Date `json:"date"`
	EventType      EventType          `json:"event_type"`
	InterviewRound *int               `json:"interview_round,omitempty"`
	PositionTitle  string             `json:"position_title"`
}

// Company defines model for Company.
type Company struct {
	ApplicationCount int                `json:"application_count"`
	CreatedAt        time.Time          `json:"created_at"`
	Id               openapi_types.UUID `json:"id"`
	Name             string             `json:"name"`
	Notes            *string            `json:"notes,omitempty"`
	Website          *string            `json:"website,omitempty"`
}

// CompanyInput defines model for CompanyInput.
type CompanyInput struct {
	Name    string  `json:"name"`
	Notes   *string `json:"notes,omitempty"`
	Website *string `json:"website,omitempty"`
}

// CompanyPatch defines model for CompanyPatch.
type CompanyPatch struct {
	Name    *string `json:"name,omitempty"`
	Notes   *string `json:"notes,omitempty"`
	Website *string `json:"website,omitempty"`
}

// Deadline defines model for Deadline.
type Deadline struct {
	ApplicationId openapi_types.UUID `json:"application_id"`
	CompanyName   string             `json:"company_name"`
	DueOn         openapi_types.Date `json:"due_on"`
	EventType     EventType          `json:"event_type"`
	Overdue       bool               `json:"overdue"`
	PositionTitle string             `json:"position_title"`
}

// Event defines model for Event.
type Event struct {
	CreatedAt      time.Time           `json:"created_at"`
	DueOn          *openapi_types.Date `json:"due_on,omitempty"`
	Id             openapi_types.UUID  `json:"id"`
	InterviewRound *int                `json:"interview_round,omitempty"`
	Note           *string             `json:"note,omitempty"`
	OccurredOn     openapi_types.Date  `json:"occurred_on"`
	Type           EventType           `json:"type"`
}

// EventType defines model for EventType.
type EventType string

// FunnelStep defines model for FunnelStep.
type FunnelStep struct {
	Rate    float64 `json:"rate"`
	Reached int     `json:"reached"`
	Stage   string  `json:"stage"`
}

// NewEvent defines model for NewEvent.
type NewEvent struct {
	// DueOn Nur bei Vorgemerkt, ChallengeErhalten und AngebotErhalten erlaubt
	DueOn      *openapi_types.Date `json:"due_on,omitempty"`
	Note       *string             `json:"note,omitempty"`
	OccurredOn openapi_types.Date  `json:"occurred_on"`
	Type       EventType           `json:"type"`
}

// Phase defines model for Phase.
type Phase string

// Problem defines model for Problem.
type Problem struct {
	Detail               *string                `json:"detail,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RejectionCount defines model for RejectionCount.
type RejectionCount struct {
	Count     int       `json:"count"`
	EventType EventType `json:"event_type"`
}

// SourceStats defines model for SourceStats.
type SourceStats struct {
	Applied          int    `json:"applied"`
	ReachedInterview int    `json:"reached_interview"`
	ReachedOffer     int    `json:"reached_offer"`
	Source           string `json:"source"`
}

// Summary defines model for Summary.
type Summary struct {
	Applied              int              `json:"applied"`
	AvgDaysToResponse    *float64         `json:"avg_days_to_response,omitempty"`
	BySource             []SourceStats    `json:"by_source"`
	MedianDaysToResponse *float64         `json:"median_days_to_response,omitempty"`
	RejectionsAfter      []RejectionCount `json:"rejections_after"`
	Responded            int              `json:"responded"`
	ResponseRate         float64          `json:"response_rate"`
}

// Id defines model for Id.
type Id = openapi_types.UUID

// ListApplicationsParams defines parameters for ListApplications.
type ListApplicationsParams struct {
	Phase  *Phase     `form:"phase,omitempty" json:"phase,omitempty"`
	Status *EventType `form:"status,omitempty" json:"status,omitempty"`

	// Q Suche in Firmenname und Stellentitel
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// ListAppointmentsParams defines parameters for ListAppointments.
type ListAppointmentsParams struct {
	// WithinDays Zeitraum ab heute (Standard 14)
	WithinDays *int `form:"within_days,omitempty" json:"within_days,omitempty"`
}

// ListDeadlinesParams defines parameters for ListDeadlines.
type ListDeadlinesParams struct {
	// WithinDays Zeitraum ab heute (Standard 7); überfällige Fristen sind immer enthalten
	WithinDays *int `form:"within_days,omitempty" json:"within_days,omitempty"`
}

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = ApplicationInput

// UpdateApplicationJSONRequestBody defines body for UpdateApplication for application/json ContentType.
type UpdateApplicationJSONRequestBody = ApplicationPatch

// AddEventJSONRequestBody defines body for AddEvent for application/json ContentType.
type AddEventJSONRequestBody = NewEvent

// CreateCompanyJSONRequestBody defines body for CreateCompany for application/json ContentType.
type CreateCompanyJSONRequestBody = CompanyInput

// UpdateCompanyJSONRequestBody defines body for UpdateCompany for application/json ContentType.
type UpdateCompanyJSONRequestBody = CompanyPatch

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/applications)
	ListApplications(w http.ResponseWriter, r *http.Request, params ListApplicationsParams)
	// CreateApplication Bewerbung inklusive erstem Ereignis (Vorgemerkt oder Beworben) anlegen
	// (POST /api/v1/applications)
	CreateApplication(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/v1/applications/{id})
	DeleteApplication(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/applications/{id})
	GetApplication(w http.ResponseWriter, r *http.Request, id Id)
	// UpdateApplication Stammdaten ändern (nicht den Status)
	// (PATCH /api/v1/applications/{id})
	UpdateApplication(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/applications/{id}/allowed-events)
	ListAllowedEvents(w http.ResponseWriter, r *http.Request, id Id)
	// AddEvent Statuswechsel als Ereignis erfassen (422 bei unerlaubtem Übergang)
	// (POST /api/v1/applications/{id}/events)
	AddEvent(w http.ResponseWriter, r *http.Request, id Id)
	// UndoLastEvent Letztes Ereignis rückgängig machen
	// (DELETE /api/v1/applications/{id}/events/latest)
	UndoLastEvent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/appointments)
	ListAppointments(w http.ResponseWriter, r *http.Request, params ListAppointmentsParams)
	// ListCompanies Alle Firmen mit Anzahl Bewerbungen
	// (GET /api/v1/companies)
	ListCompanies(w http.ResponseWriter, r *http.Request)
	// CreateCompany Firma anlegen
	// (POST /api/v1/companies)
	CreateCompany(w http.ResponseWriter, r *http.Request)
	// DeleteCompany Firma löschen (nur ohne Bewerbungen, sonst 409)
	// (DELETE /api/v1/companies/{id})
	DeleteCompany(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/companies/{id})
	GetCompany(w http.ResponseWriter, r *http.Request, id Id)
	// UpdateCompany Firma ändern (nur gesetzte Felder; "" löscht optionale Felder)
	// (PATCH /api/v1/companies/{id})
	UpdateCompany(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/deadlines)
	ListDeadlines(w http.ResponseWriter, r *http.Request, params ListDeadlinesParams)

	// (GET /api/v1/stats/funnel)
	GetFunnel(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/stats/summary)
	GetSummary(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListApplicationsParams

	// ------------- Optional query parameter "phase" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "phase", r.URL.Query(), &params.Phase, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "phase"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "phase", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApplications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateApplication(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApplication(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApplication operation middleware
func (siw *ServerInterfaceWrapper) DeleteApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApplication operation middleware
func (siw *ServerInterfaceWrapper) GetApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateApplication operation middleware
func (siw *ServerInterfaceWrapper) UpdateApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAllowedEvents operation middleware
func (siw *ServerInterfaceWrapper) ListAllowedEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAllowedEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddEvent operation middleware
func (siw *ServerInterfaceWrapper) AddEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UndoLastEvent operation middleware
func (siw *ServerInterfaceWrapper) UndoLastEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UndoLastEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAppointments operation middleware
func (siw *ServerInterfaceWrapper) ListAppointments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAppointmentsParams

	// ------------- Optional query parameter "within_days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "within_days", r.URL.Query(), &params.WithinDays, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "within_days"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "within_days", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAppointments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCompanies operation middleware
func (siw *ServerInterfaceWrapper) ListCompanies(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCompanies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCompany operation middleware
func (siw *ServerInterfaceWrapper) CreateCompany(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCompany(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCompany operation middleware
func (siw *ServerInterfaceWrapper) DeleteCompany(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCompany(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCompany operation middleware
func (siw *ServerInterfaceWrapper) GetCompany(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCompany(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCompany operation middleware
func (siw *ServerInterfaceWrapper) UpdateCompany(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCompany(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDeadlines operation middleware
func (siw *ServerInterfaceWrapper) ListDeadlines(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDeadlinesParams

	// ------------- Optional query parameter "within_days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "within_days", r.URL.Query(), &params.WithinDays, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "within_days"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "within_days", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeadlines(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFunnel operation middleware
func (siw *ServerInterfaceWrapper) GetFunnel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFunnel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSummary operation middleware
func (siw *ServerInterfaceWrapper) GetSummary(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/companies", wrapper.ListCompanies)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/companies", wrapper.CreateCompany)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/companies/{id}", wrapper.DeleteCompany)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/companies/{id}", wrapper.GetCompany)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/companies/{id}", wrapper.UpdateCompany)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/applications", wrapper.ListApplications)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/applications", wrapper.CreateApplication)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/applications/{id}", wrapper.DeleteApplication)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/applications/{id}", wrapper.GetApplication)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/applications/{id}", wrapper.UpdateApplication)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/applications/{id}/events", wrapper.AddEvent)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/applications/{id}/events/latest", wrapper.UndoLastEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/applications/{id}/allowed-events", wrapper.ListAllowedEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/deadlines", wrapper.ListDeadlines)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/appointments", wrapper.ListAppointments)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/stats/funnel", wrapper.GetFunnel)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/stats/summary", wrapper.GetSummary)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type ListApplicationsRequestObject struct {
	Params ListApplicationsParams
}

type ListApplicationsResponseObject interface {
	VisitListApplicationsResponse(w http.ResponseWriter) error
}

type ListApplications200JSONResponse []ApplicationSummary

func (response ListApplications200JSONResponse) VisitListApplicationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListApplicationsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListApplicationsdefaultApplicationProblemPlusJSONResponse) VisitListApplicationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplicationRequestObject struct {
	Body *CreateApplicationJSONRequestBody
}

type CreateApplicationResponseObject interface {
	VisitCreateApplicationResponse(w http.ResponseWriter) error
}

type CreateApplication201JSONResponse Application

func (response CreateApplication201JSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplicationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateApplicationdefaultApplicationProblemPlusJSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteApplicationRequestObject struct {
	Id Id `json:"id"`
}

type DeleteApplicationResponseObject interface {
	VisitDeleteApplicationResponse(w http.ResponseWriter) error
}

type DeleteApplication204Response struct {
}

func (response DeleteApplication204Response) VisitDeleteApplicationResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApplicationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteApplicationdefaultApplicationProblemPlusJSONResponse) VisitDeleteApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetApplicationRequestObject struct {
	Id Id `json:"id"`
}

type GetApplicationResponseObject interface {
	VisitGetApplicationResponse(w http.ResponseWriter) error
}

type GetApplication200JSONResponse Application

func (response GetApplication200JSONResponse) VisitGetApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApplicationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetApplicationdefaultApplicationProblemPlusJSONResponse) VisitGetApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateApplicationRequestObject struct {
	Id   Id `json:"id"`
	Body *UpdateApplicationJSONRequestBody
}

type UpdateApplicationResponseObject interface {
	VisitUpdateApplicationResponse(w http.ResponseWriter) error
}

type UpdateApplication200JSONResponse Application

func (response UpdateApplication200JSONResponse) VisitUpdateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateApplicationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateApplicationdefaultApplicationProblemPlusJSONResponse) VisitUpdateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListAllowedEventsRequestObject struct {
	Id Id `json:"id"`
}

type ListAllowedEventsResponseObject interface {
	VisitListAllowedEventsResponse(w http.ResponseWriter) error
}

type ListAllowedEvents200JSONResponse []EventType

func (response ListAllowedEvents200JSONResponse) VisitListAllowedEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAllowedEventsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListAllowedEventsdefaultApplicationProblemPlusJSONResponse) VisitListAllowedEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AddEventRequestObject struct {
	Id   Id `json:"id"`
	Body *AddEventJSONRequestBody
}

type AddEventResponseObject interface {
	VisitAddEventResponse(w http.ResponseWriter) error
}

type AddEvent201JSONResponse Event

func (response AddEvent201JSONResponse) VisitAddEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AddEventdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response AddEventdefaultApplicationProblemPlusJSONResponse) VisitAddEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UndoLastEventRequestObject struct {
	Id Id `json:"id"`
}

type UndoLastEventResponseObject interface {
	VisitUndoLastEventResponse(w http.ResponseWriter) error
}

type UndoLastEvent200JSONResponse Application

func (response UndoLastEvent200JSONResponse) VisitUndoLastEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UndoLastEventdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UndoLastEventdefaultApplicationProblemPlusJSONResponse) VisitUndoLastEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListAppointmentsRequestObject struct {
	Params ListAppointmentsParams
}

type ListAppointmentsResponseObject interface {
	VisitListAppointmentsResponse(w http.ResponseWriter) error
}

type ListAppointments200JSONResponse []Appointment

func (response ListAppointments200JSONResponse) VisitListAppointmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAppointmentsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListAppointmentsdefaultApplicationProblemPlusJSONResponse) VisitListAppointmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListCompaniesRequestObject struct {
}

type ListCompaniesResponseObject interface {
	VisitListCompaniesResponse(w http.ResponseWriter) error
}

type ListCompanies200JSONResponse []Company

func (response ListCompanies200JSONResponse) VisitListCompaniesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCompaniesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListCompaniesdefaultApplicationProblemPlusJSONResponse) VisitListCompaniesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCompanyRequestObject struct {
	Body *CreateCompanyJSONRequestBody
}

type CreateCompanyResponseObject interface {
	VisitCreateCompanyResponse(w http.ResponseWriter) error
}

type CreateCompany201JSONResponse Company

func (response CreateCompany201JSONResponse) VisitCreateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCompanydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateCompanydefaultApplicationProblemPlusJSONResponse) VisitCreateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCompanyRequestObject struct {
	Id Id `json:"id"`
}

type DeleteCompanyResponseObject interface {
	VisitDeleteCompanyResponse(w http.ResponseWriter) error
}

type DeleteCompany204Response struct {
}

func (response DeleteCompany204Response) VisitDeleteCompanyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCompanydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteCompanydefaultApplicationProblemPlusJSONResponse) VisitDeleteCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetCompanyRequestObject struct {
	Id Id `json:"id"`
}

type GetCompanyResponseObject interface {
	VisitGetCompanyResponse(w http.ResponseWriter) error
}

type GetCompany200JSONResponse Company

func (response GetCompany200JSONResponse) VisitGetCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCompanydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetCompanydefaultApplicationProblemPlusJSONResponse) VisitGetCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCompanyRequestObject struct {
	Id   Id `json:"id"`
	Body *UpdateCompanyJSONRequestBody
}

type UpdateCompanyResponseObject interface {
	VisitUpdateCompanyResponse(w http.ResponseWriter) error
}

type UpdateCompany200JSONResponse Company

func (response UpdateCompany200JSONResponse) VisitUpdateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCompanydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateCompanydefaultApplicationProblemPlusJSONResponse) VisitUpdateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeadlinesRequestObject struct {
	Params ListDeadlinesParams
}

type ListDeadlinesResponseObject interface {
	VisitListDeadlinesResponse(w http.ResponseWriter) error
}

type ListDeadlines200JSONResponse []Deadline

func (response ListDeadlines200JSONResponse) VisitListDeadlinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeadlinesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListDeadlinesdefaultApplicationProblemPlusJSONResponse) VisitListDeadlinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetFunnelRequestObject struct {
}

type GetFunnelResponseObject interface {
	VisitGetFunnelResponse(w http.ResponseWriter) error
}

type GetFunnel200JSONResponse []FunnelStep

func (response GetFunnel200JSONResponse) VisitGetFunnelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetFunneldefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetFunneldefaultApplicationProblemPlusJSONResponse) VisitGetFunnelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSummaryRequestObject struct {
}

type GetSummaryResponseObject interface {
	VisitGetSummaryResponse(w http.ResponseWriter) error
}

type GetSummary200JSONResponse Summary

func (response GetSummary200JSONResponse) VisitGetSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSummarydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSummarydefaultApplicationProblemPlusJSONResponse) VisitGetSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/v1/applications)
	ListApplications(ctx context.Context, request ListApplicationsRequestObject) (ListApplicationsResponseObject, error)
	// CreateApplication Bewerbung inklusive erstem Ereignis (Vorgemerkt oder Beworben) anlegen
	// (POST /api/v1/applications)
	CreateApplication(ctx context.Context, request CreateApplicationRequestObject) (CreateApplicationResponseObject, error)

	// (DELETE /api/v1/applications/{id})
	DeleteApplication(ctx context.Context, request DeleteApplicationRequestObject) (DeleteApplicationResponseObject, error)

	// (GET /api/v1/applications/{id})
	GetApplication(ctx context.Context, request GetApplicationRequestObject) (GetApplicationResponseObject, error)
	// UpdateApplication Stammdaten ändern (nicht den Status)
	// (PATCH /api/v1/applications/{id})
	UpdateApplication(ctx context.Context, request UpdateApplicationRequestObject) (UpdateApplicationResponseObject, error)

	// (GET /api/v1/applications/{id}/allowed-events)
	ListAllowedEvents(ctx context.Context, request ListAllowedEventsRequestObject) (ListAllowedEventsResponseObject, error)
	// AddEvent Statuswechsel als Ereignis erfassen (422 bei unerlaubtem Übergang)
	// (POST /api/v1/applications/{id}/events)
	AddEvent(ctx context.Context, request AddEventRequestObject) (AddEventResponseObject, error)
	// UndoLastEvent Letztes Ereignis rückgängig machen
	// (DELETE /api/v1/applications/{id}/events/latest)
	UndoLastEvent(ctx context.Context, request UndoLastEventRequestObject) (UndoLastEventResponseObject, error)

	// (GET /api/v1/appointments)
	ListAppointments(ctx context.Context, request ListAppointmentsRequestObject) (ListAppointmentsResponseObject, error)
	// ListCompanies Alle Firmen mit Anzahl Bewerbungen
	// (GET /api/v1/companies)
	ListCompanies(ctx context.Context, request ListCompaniesRequestObject) (ListCompaniesResponseObject, error)
	// CreateCompany Firma anlegen
	// (POST /api/v1/companies)
	CreateCompany(ctx context.Context, request CreateCompanyRequestObject) (CreateCompanyResponseObject, error)
	// DeleteCompany Firma löschen (nur ohne Bewerbungen, sonst 409)
	// (DELETE /api/v1/companies/{id})
	DeleteCompany(ctx context.Context, request DeleteCompanyRequestObject) (DeleteCompanyResponseObject, error)

	// (GET /api/v1/companies/{id})
	GetCompany(ctx context.Context, request GetCompanyRequestObject) (GetCompanyResponseObject, error)
	// UpdateCompany Firma ändern (nur gesetzte Felder; "" löscht optionale Felder)
	// (PATCH /api/v1/companies/{id})
	UpdateCompany(ctx context.Context, request UpdateCompanyRequestObject) (UpdateCompanyResponseObject, error)

	// (GET /api/v1/deadlines)
	ListDeadlines(ctx context.Context, request ListDeadlinesRequestObject) (ListDeadlinesResponseObject, error)

	// (GET /api/v1/stats/funnel)
	GetFunnel(ctx context.Context, request GetFunnelRequestObject) (GetFunnelResponseObject, error)

	// (GET /api/v1/stats/summary)
	GetSummary(ctx context.Context, request GetSummaryRequestObject) (GetSummaryResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListApplications operation middleware
func (sh *strictHandler) ListApplications(w http.ResponseWriter, r *http.Request, params ListApplicationsParams) {
	var request ListApplicationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListApplications(ctx, request.(ListApplicationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApplications")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListApplicationsResponseObject); ok {
		if err := validResponse.VisitListApplicationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateApplication operation middleware
func (sh *strictHandler) CreateApplication(w http.ResponseWriter, r *http.Request) {
	var request CreateApplicationRequestObject

	var body CreateApplicationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateApplication(ctx, request.(CreateApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateApplication")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateApplicationResponseObject); ok {
		if err := validResponse.VisitCreateApplicationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApplication operation middleware
func (sh *strictHandler) DeleteApplication(w http.ResponseWriter, r *http.Request, id Id) {
	var request DeleteApplicationRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApplication(ctx, request.(DeleteApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApplication")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteApplicationResponseObject); ok {
		if err := validResponse.VisitDeleteApplicationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApplication operation middleware
func (sh *strictHandler) GetApplication(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetApplicationRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApplication(ctx, request.(GetApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApplication")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApplicationResponseObject); ok {
		if err := validResponse.VisitGetApplicationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateApplication operation middleware
func (sh *strictHandler) UpdateApplication(w http.ResponseWriter, r *http.Request, id Id) {
	var request UpdateApplicationRequestObject

	request.Id = id

	var body UpdateApplicationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateApplication(ctx, request.(UpdateApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateApplication")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateApplicationResponseObject); ok {
		if err := validResponse.VisitUpdateApplicationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAllowedEvents operation middleware
func (sh *strictHandler) ListAllowedEvents(w http.ResponseWriter, r *http.Request, id Id) {
	var request ListAllowedEventsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAllowedEvents(ctx, request.(ListAllowedEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAllowedEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAllowedEventsResponseObject); ok {
		if err := validResponse.VisitListAllowedEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddEvent operation middleware
func (sh *strictHandler) AddEvent(w http.ResponseWriter, r *http.Request, id Id) {
	var request AddEventRequestObject

	request.Id = id

	var body AddEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddEvent(ctx, request.(AddEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddEventResponseObject); ok {
		if err := validResponse.VisitAddEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UndoLastEvent operation middleware
func (sh *strictHandler) UndoLastEvent(w http.ResponseWriter, r *http.Request, id Id) {
	var request UndoLastEventRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UndoLastEvent(ctx, request.(UndoLastEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UndoLastEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UndoLastEventResponseObject); ok {
		if err := validResponse.VisitUndoLastEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAppointments operation middleware
func (sh *strictHandler) ListAppointments(w http.ResponseWriter, r *http.Request, params ListAppointmentsParams) {
	var request ListAppointmentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAppointments(ctx, request.(ListAppointmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAppointments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAppointmentsResponseObject); ok {
		if err := validResponse.VisitListAppointmentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCompanies operation middleware
func (sh *strictHandler) ListCompanies(w http.ResponseWriter, r *http.Request) {
	var request ListCompaniesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCompanies(ctx, request.(ListCompaniesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCompanies")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCompaniesResponseObject); ok {
		if err := validResponse.VisitListCompaniesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCompany operation middleware
func (sh *strictHandler) CreateCompany(w http.ResponseWriter, r *http.Request) {
	var request CreateCompanyRequestObject

	var body CreateCompanyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCompany(ctx, request.(CreateCompanyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCompany")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCompanyResponseObject); ok {
		if err := validResponse.VisitCreateCompanyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCompany operation middleware
func (sh *strictHandler) DeleteCompany(w http.ResponseWriter, r *http.Request, id Id) {
	var request DeleteCompanyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCompany(ctx, request.(DeleteCompanyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCompany")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCompanyResponseObject); ok {
		if err := validResponse.VisitDeleteCompanyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCompany operation middleware
func (sh *strictHandler) GetCompany(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetCompanyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCompany(ctx, request.(GetCompanyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCompany")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCompanyResponseObject); ok {
		if err := validResponse.VisitGetCompanyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCompany operation middleware
func (sh *strictHandler) UpdateCompany(w http.ResponseWriter, r *http.Request, id Id) {
	var request UpdateCompanyRequestObject

	request.Id = id

	var body UpdateCompanyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCompany(ctx, request.(UpdateCompanyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCompany")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCompanyResponseObject); ok {
		if err := validResponse.VisitUpdateCompanyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDeadlines operation middleware
func (sh *strictHandler) ListDeadlines(w http.ResponseWriter, r *http.Request, params ListDeadlinesParams) {
	var request ListDeadlinesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDeadlines(ctx, request.(ListDeadlinesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDeadlines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDeadlinesResponseObject); ok {
		if err := validResponse.VisitListDeadlinesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFunnel operation middleware
func (sh *strictHandler) GetFunnel(w http.ResponseWriter, r *http.Request) {
	var request GetFunnelRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFunnel(ctx, request.(GetFunnelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFunnel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFunnelResponseObject); ok {
		if err := validResponse.VisitGetFunnelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSummary operation middleware
func (sh *strictHandler) GetSummary(w http.ResponseWriter, r *http.Request) {
	var request GetSummaryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSummary(ctx, request.(GetSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSummary")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSummaryResponseObject); ok {
		if err := validResponse.VisitGetSummaryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FrNcts4En4VFHYPcS1jKX87NcpJcexUdlLZVJSZw0xSKpBskYhBgMGPtU5Kb7LHPMOe5uYX2wIh/omg",
	"RDuSMlNzSSyyAXT3193oH37BkchywYFrhSdfcE4kyUCDLH69jO2/lOMJzolOcYA5yQBPMI1xgCV8MlRC",
	"jCdaGgiwilLIiF2xEDIjGk+wMQWlvs7tKqUl5QlerVZ2scoFV1Cc80aKkEFm/4wE18C1/ZPkOaMR0VTw",
	"Ue4o/vFRCW7f1Wf9XcICT/DfRrUgI/dWjcp9ixNjUJGkud0OT/AFpAwk4iRK0duLM/Tj4yc/YEu2Xmu3",
	"ntYM2J+5FDlITR3P9jjCr+c0HiBxUJE7BX7xEEggGuI50a39YqLhvqYZ+DaFqxI3qiFTu9RxbsnxqtqI",
	"SEmu7e+BMnwU4dxI5mWfiVpRnZdcaFDeN3lKFOyEsSCy1EJRe8hcU838alTCyKjnlSbaDFPSO7t2FWCT",
	"x7cEZdX0i9+cozRMZcMQOiJVXJaqaRlGi6EK/g8VEyL8CFGBcMN0X/Lc6G+23wWVSs+LE3dp8DUsK0tr",
	"mExG/vMKeKJTPHkwHo+D7TbUoH7oJa5sqkH5xL9v12waax7ZJRnlFW/BNqNqC7EL/RbwHaSbKt2B4Rui",
	"o/SbMfzrgbFNpzOTZUReHz6yD9yHkdIa5oK3VliX960QOfB5bGAo/f6D7Z8zoraCaFvtPX4oKNfZOvS1",
	"jaWRpOzNYAr8hgDq2HaPb4EB5RrkFYXlXArD4wYP9k0CchD8G7hsKGI3LA3m1yL7lH/mdtmu+EgYh01X",
	"jLukVQNx7MWvP91ZQqioHqDN4sS15loJQFfsLVrrufpLxjfD+o7Ae4sg35CzTbzLuwvWtkjUcxH+wSTq",
	"cP8cSMwohyPFj+FXwh0jiLgCGZvm6aEQDAj/DpHDCVvz5LOe8ytv8L5LcLiFcgfiOSgcW1P1gi2iyEgJ",
	"8VCmbom1Ly6tNd88uRWlehF4tz4buMnsbr8ImUAG8lLjAD+DpZAh2L1mkQTglCcvQOWSQJTiAJ+lhDHg",
	"CZzLlDANvPlsGiaQgFv9stQnDvBPwDlwBpJrkuAAT3kCodCNLdZP7H9cZFnrWZgAg5Rb7qahIomV+lcj",
	"DUSXCXwWSUH8E1AOb+2zDFhseII/eNR+YTgHNtOQd81Qdu57YULWQI+bLHRmIIFEKfTYiNKWxZ3+5sjq",
	"vQLHgA+1qpTr8Fy7Qbuv8tpIFAJFNbQB6iCHDI/RBhQIJCMmtLreacNc+CKxL2wf1zs8juHT6psyD2/4",
	"QQgSqLbWE+DppaZXhc0loKKUCaWAe62q0TgjcVxEScLeNIBynbkN6EATynYk9F3r6i8DSqVtN7u1cjay",
	"cp9+3oL9iwp+VuZ1mwVab7p3p/tsg9HW9dKfY82KOnSmiVZdFos7rc9P1443rwL/djKxWIDs8fi+btem",
	"yzu6oOLLx8TmiV6h+4rmrQKTq2Qek2s112JeNn4HBrzwel4LOajL2cTF0+vMIKaE35UdWZqmmpOFBjmY",
	"qw2b9jDmOIn7jcYxOh98W/jSrDX05Umb23oEbELQtYhVkb8sRPci+AXkkjAb0dCV4OgZLEGGxt6yp+hf",
	"EINEsyICLCFKFTC0pDJGhCl0LoEmnCqUgMqBRilI/RTZBeRSG2AM1isRyISGGikapYgYhWLI0GfDQH/W",
	"COSCKGXvlXK/U7Tu+S9BxsCLs/pGDOheORM4QQkwCguQ+vQ9r+LXBFcCqfvvJIkuQaLpm5c4wFcglVPB",
	"g9Px6bhs1JCc4gl+dDo+fYSDYpxS2MyI5HR09WDU4KR4nkAR4ayLuS5ujCf4FVV62iQMWgOb39azmk8G",
	"5HU9rCnbHgNnJgX1ahX4N6uaKcN2a0XZTROZmSgFRDm6oDIDbk8oMoOZtihzTTUwHHjZ+NTiYEd/cvVh",
	"Y970cDzeMmvqzpgGebintdjx8u4cquEXQWW8Cdx85TFIDeizAamKeBHDghjW232vBGxMvQKsSWINo3kM",
	"/uBqNI99nRU5fEOQ9ZQPlH4m4utb6WygqlyLYtUOVjZrWXUwe3CI832Y2MyUQXJ3ravylqz1jii/ZEbR",
	"K0AWUMjqOHevzpWRsHGurIROEOEMXJXhB3IVeAPI6AuNVy4kM9DQBfp58XwT6Ja2H3dD+gtgN/9TUbp/",
	"c/RGuxegt3I4PpY91CBmVFe43X9HMyiaOnt3znZM921Yk4xextgGuLzsjLWV+HPR6z6qS7se3SCXPhqE",
	"L8qIugefnmmSZVarHLlNObrHaZRqZNMKl5uc3MllR4QxsYT4fj3Y788DHOm5ozzGBdfqAO6616ZModc3",
	"X6NUaVBlbQ+V89jl/I/gOFvhqGG4m0t6L9lp7EA7kCPW0/fj3qmNQ9uWcO4y8f04XqNgaNUKLt0Hju49",
	"fviwaEAZXhpdhm7+G4JMCE/u6JbODkaMaFB62736M4/FK6J0DfD3vrGKD5xsYfT25vfoMrn5yhOaZLbM",
	"53tA5JVNV6GBg2ycgtbHHNBfy7nszpKpJuyc2tbcr0C1JCZDJEQpGA3o3kwTHhMZowePT3rKkSXVKXVN",
	"hc3ChGYmw5NH/3xSTKPcr3HQKfCPVqOUmhgUxLnSkAKPAb0Dme0j1ylc0Vbsuu10buZDYTuSZxXVMbRV",
	"zp4HaMpVsAEiLE9JCJoqmwJ9s39NbbfD7V3knlP+maSs2UxpeJej21nelVId5vppTZ6PfAVVeB20pLNq",
	"Jp7KrFK/z6oHVmRNbA5fjW3K5Pazlyg3EomUA2q1J5TgSqPH4x9P/FbXV8X1SjU+BvSFbN8ct5rOtffy",
	"7Cgu+V3Ksi247LMkc/ZbV2NG2u5xkZygC2AxyKfoPX6P1yaukcjdrKx8fbLDkeP1Bxzbr6fnFdU3ZBk/",
	"nDxFN7+HIBc3XxmjCaALSYtOtqI8RjTLQCLguppg/5kTklJjQ+7Yfy8WwCttHCwTUZpoNVoU8/petF+A",
	"dhP9oyQijY8HhuQiBfX9mTaLg6tJ1fPAPj2VzfADRpnyCI8y7AcgNmfauybqF+XnZ2XgWAXVk2ai1njc",
	"2Gn1YfX/AQA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
