//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventType.
const (
	Absage             EventType = "Absage"
	AngebotAbgelehnt   EventType = "AngebotAbgelehnt"
	AngebotAngenommen  EventType = "AngebotAngenommen"
	AngebotErhalten    EventType = "AngebotErhalten"
	Beworben           EventType = "Beworben"
	ChallengeAbgegeben EventType = "ChallengeAbgegeben"
	ChallengeErhalten  EventType = "ChallengeErhalten"
	Interview          EventType = "Interview"
	KeineRueckmeldung  EventType = "KeineRueckmeldung"
	Kennenlerntag      EventType = "Kennenlerntag"
	ScreeningGespraech EventType = "ScreeningGespraech"
	Vorgemerkt         EventType = "Vorgemerkt"
	Zurueckgezogen     EventType = "Zurueckgezogen"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case Absage:
		return true
	case AngebotAbgelehnt:
		return true
	case AngebotAngenommen:
		return true
	case AngebotErhalten:
		return true
	case Beworben:
		return true
	case ChallengeAbgegeben:
		return true
	case ChallengeErhalten:
		return true
	case Interview:
		return true
	case KeineRueckmeldung:
		return true
	case Kennenlerntag:
		return true
	case ScreeningGespraech:
		return true
	case Vorgemerkt:
		return true
	case Zurueckgezogen:
		return true
	default:
		return false
	}
}

// Defines values for Phase.
const (
	Abgeschlossen Phase = "Abgeschlossen"
	Aktiv         Phase = "Aktiv"
	Vorbereitung  Phase = "Vorbereitung"
)

// Valid indicates whether the value is a known member of the Phase enum.
func (e Phase) Valid() bool {
	switch e {
	case Abgeschlossen:
		return true
	case Aktiv:
		return true
	case Vorbereitung:
		return true
	default:
		return false
	}
}

// Application defines model for Application.
type Application struct {
	CompanyId     openapi_types.UUID `json:"company_id"`
	CompanyName   string             `json:"company_name"`
	CreatedAt     time.Time          `json:"created_at"`
	Events        []Event            `json:"events"`
	Id            openapi_types.UUID `json:"id"`
	JobUrl        *string            `json:"job_url,omitempty"`
	Location      *string            `json:"location,omitempty"`
	Notes         *string            `json:"notes,omitempty"`
	Phase         Phase              `json:"phase"`
	PositionTitle string             `json:"position_title"`
	Source        *string            `json:"source,omitempty"`
	Status        EventType          `json:"status"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// ApplicationInput defines model for ApplicationInput.
type ApplicationInput struct {
	CompanyId     openapi_types.UUID `json:"company_id"`
	FirstEvent    NewEvent           `json:"first_event"`
	JobUrl        *string            `json:"job_url,omitempty"`
	Location      *string            `json:"location,omitempty"`
	Notes         *string            `json:"notes,omitempty"`
	PositionTitle string             `json:"position_title"`
	Source        *string            `json:"source,omitempty"`
}

// ApplicationPatch Nur gesetzte Felder werden geändert; ein leerer String löscht ein optionales Feld.
type ApplicationPatch struct {
	CompanyId     *openapi_types.UUID `json:"company_id,omitempty"`
	JobUrl        *string             `json:"job_url,omitempty"`
	Location      *string             `json:"location,omitempty"`
	Notes         *string             `json:"notes,omitempty"`
	PositionTitle *string             `json:"position_title,omitempty"`
	Source        *string             `json:"source,omitempty"`
}

// ApplicationSummary defines model for ApplicationSummary.
type ApplicationSummary struct {
	CompanyId     openapi_types.UUID  `json:"company_id"`
	CompanyName   string              `json:"company_name"`
	Id            openapi_types.UUID  `json:"id"`
	LastEventOn   openapi_types.Date  `json:"last_event_on"`
	OpenDueOn     *openapi_types.Date `json:"open_due_on,omitempty"`
	Phase         Phase               `json:"phase"`
	PositionTitle string              `json:"position_title"`
	Status        EventType           `json:"status"`
	UpdatedAt     time.Time           `json:"updated_at"`
}

// Appointment defines model for Appointment.
type Appointment struct {
	ApplicationId  openapi_types.UUID `json:"application_id"`
	CompanyName    string             `json:"company_name"`
	Date           openapi_types.Date `json:"date"`
	EventType      EventType          `json:"event_type"`
	InterviewRound *int               `json:"interview_round,omitempty"`
	PositionTitle  string             `json:"position_title"`
}

// Company defines model for Company.
type Company struct {
	ApplicationCount int                `json:"application_count"`
	CreatedAt        time.Time          `json:"created_at"`
	Id               openapi_types.UUID `json:"id"`
	Name             string             `json:"name"`
	Notes            *string            `json:"notes,omitempty"`
	Website          *string            `json:"website,omitempty"`
}

// CompanyInput defines model for CompanyInput.
type CompanyInput struct {
	Name    string  `json:"name"`
	Notes   *string `json:"notes,omitempty"`
	Website *string `json:"website,omitempty"`
}

// CompanyPatch Nur gesetzte Felder werden geändert; ein leerer String löscht ein optionales Feld.
type CompanyPatch struct {
	Name    *string `json:"name,omitempty"`
	Notes   *string `json:"notes,omitempty"`
	Website *string `json:"website,omitempty"`
}

// Cv Lebenslauf. end fehlt = bis heute. updated_at wird beim Speichern ignoriert. Solange kein Lebenslauf gespeichert ist, liefert GET eine leere Struktur (person.name leer, Listen leer, ohne updated_at).
type Cv struct {
	Education  []CvEducation  `json:"education"`
	Experience []CvExperience `json:"experience"`
	Languages  []CvLanguage   `json:"languages"`
	Person     CvPerson       `json:"person"`
	Projects   []CvProject    `json:"projects"`
	Skills     []CvSkillGroup `json:"skills"`
	Summary    *string        `json:"summary,omitempty"`
	UpdatedAt  *time.Time     `json:"updated_at,omitempty"`
}

// CvEducation defines model for CvEducation.
type CvEducation struct {
	Degree  string  `json:"degree"`
	Details *string `json:"details,omitempty"`

	// End Jahr oder Jahr-Monat, z. B. 2024 oder 2024-03
	End         *CvPeriod `json:"end,omitempty"`
	Institution string    `json:"institution"`

	// Start Jahr oder Jahr-Monat, z. B. 2024 oder 2024-03
	Start CvPeriod `json:"start"`
}

// CvExperience defines model for CvExperience.
type CvExperience struct {
	// End Jahr oder Jahr-Monat, z. B. 2024 oder 2024-03
	End          *CvPeriod `json:"end,omitempty"`
	Highlights   []string  `json:"highlights"`
	Location     *string   `json:"location,omitempty"`
	Organization string    `json:"organization"`
	Role         string    `json:"role"`

	// Start Jahr oder Jahr-Monat, z. B. 2024 oder 2024-03
	Start CvPeriod `json:"start"`
}

// CvLanguage defines model for CvLanguage.
type CvLanguage struct {
	Language string `json:"language"`
	Level    string `json:"level"`
}

// CvLink defines model for CvLink.
type CvLink struct {
	Label string `json:"label"`
	Url   string `json:"url"`
}

// CvPeriod Jahr oder Jahr-Monat, z. B. 2024 oder 2024-03
type CvPeriod = string

// CvPerson defines model for CvPerson.
type CvPerson struct {
	Email    *string  `json:"email,omitempty"`
	Headline *string  `json:"headline,omitempty"`
	Links    []CvLink `json:"links"`
	Location *string  `json:"location,omitempty"`
	Name     string   `json:"name"`
	Phone    *string  `json:"phone,omitempty"`
}

// CvProject defines model for CvProject.
type CvProject struct {
	Description  *string  `json:"description,omitempty"`
	Name         string   `json:"name"`
	Technologies []string `json:"technologies"`
	Url          *string  `json:"url,omitempty"`
}

// CvSkillGroup defines model for CvSkillGroup.
type CvSkillGroup struct {
	Category string   `json:"category"`
	Items    []string `json:"items"`
}

// Deadline defines model for Deadline.
type Deadline struct {
	ApplicationId openapi_types.UUID `json:"application_id"`
	CompanyName   string             `json:"company_name"`
	DueOn         openapi_types.Date `json:"due_on"`
	EventType     EventType          `json:"event_type"`
	Overdue       bool               `json:"overdue"`
	PositionTitle string             `json:"position_title"`
}

// Event defines model for Event.
type Event struct {
	CreatedAt      time.Time           `json:"created_at"`
	DueOn          *openapi_types.Date `json:"due_on,omitempty"`
	Id             openapi_types.UUID  `json:"id"`
	InterviewRound *int                `json:"interview_round,omitempty"`
	Note           *string             `json:"note,omitempty"`
	OccurredOn     openapi_types.Date  `json:"occurred_on"`
	Type           EventType           `json:"type"`
}

// EventType defines model for EventType.
type EventType string

// FunnelStep defines model for FunnelStep.
type FunnelStep struct {
	Rate    float64 `json:"rate"`
	Reached int     `json:"reached"`
	Stage   string  `json:"stage"`
}

// NewEvent defines model for NewEvent.
type NewEvent struct {
	// DueOn Nur bei Vorgemerkt, ChallengeErhalten und AngebotErhalten erlaubt
	DueOn      *openapi_types.Date `json:"due_on,omitempty"`
	Note       *string             `json:"note,omitempty"`
	OccurredOn openapi_types.Date  `json:"occurred_on"`
	Type       EventType           `json:"type"`
}

// Phase defines model for Phase.
type Phase string

// Problem defines model for Problem.
type Problem struct {
	Attempted            *EventType             `json:"attempted,omitempty"`
	Detail               *string                `json:"detail,omitempty"`
	Field                *string                `json:"field,omitempty"`
	From                 *EventType             `json:"from,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RejectionCount defines model for RejectionCount.
type RejectionCount struct {
	Count     int       `json:"count"`
	EventType EventType `json:"event_type"`
}

// SourceStats defines model for SourceStats.
type SourceStats struct {
	Applied          int    `json:"applied"`
	ReachedInterview int    `json:"reached_interview"`
	ReachedOffer     int    `json:"reached_offer"`
	Source           string `json:"source"`
}

// Summary defines model for Summary.
type Summary struct {
	Applied              int              `json:"applied"`
	AvgDaysToResponse    *float64         `json:"avg_days_to_response,omitempty"`
	BySource             []SourceStats    `json:"by_source"`
	MedianDaysToResponse *float64         `json:"median_days_to_response,omitempty"`
	RejectionsAfter      []RejectionCount `json:"rejections_after"`
	Responded            int              `json:"responded"`
	ResponseRate         float64          `json:"response_rate"`
}

// Id defines model for Id.
type Id = openapi_types.UUID

// ListApplicationsParams defines parameters for ListApplications.
type ListApplicationsParams struct {
	Phase  *Phase     `form:"phase,omitempty" json:"phase,omitempty"`
	Status *EventType `form:"status,omitempty" json:"status,omitempty"`

	// Q Suche in Firmenname und Stellentitel
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// ListAppointmentsParams defines parameters for ListAppointments.
type ListAppointmentsParams struct {
	// WithinDays Zeitraum ab heute (Standard 14)
	WithinDays *int `form:"within_days,omitempty" json:"within_days,omitempty"`
}

// ListDeadlinesParams defines parameters for ListDeadlines.
type ListDeadlinesParams struct {
	// WithinDays Zeitraum ab heute (Standard 7); überfällige Fristen sind immer enthalten
	WithinDays *int `form:"within_days,omitempty" json:"within_days,omitempty"`
}

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = ApplicationInput

// UpdateApplicationJSONRequestBody defines body for UpdateApplication for application/json ContentType.
type UpdateApplicationJSONRequestBody = ApplicationPatch

// AddEventJSONRequestBody defines body for AddEvent for application/json ContentType.
type AddEventJSONRequestBody = NewEvent

// CreateCompanyJSONRequestBody defines body for CreateCompany for application/json ContentType.
type CreateCompanyJSONRequestBody = CompanyInput

// UpdateCompanyJSONRequestBody defines body for UpdateCompany for application/json ContentType.
type UpdateCompanyJSONRequestBody = CompanyPatch

// SaveCvJSONRequestBody defines body for SaveCv for application/json ContentType.
type SaveCvJSONRequestBody = Cv

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["attempted"]; found {
		err = json.Unmarshal(raw, &a.Attempted)
		if err != nil {
			return fmt.Errorf("error reading 'attempted': %w", err)
		}
		delete(object, "attempted")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if raw, found := object["from"]; found {
		err = json.Unmarshal(raw, &a.From)
		if err != nil {
			return fmt.Errorf("error reading 'from': %w", err)
		}
		delete(object, "from")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Attempted != nil {
		object["attempted"], err = json.Marshal(a.Attempted)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attempted': %w", err)
		}
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Field != nil {
		object["field"], err = json.Marshal(a.Field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field': %w", err)
		}
	}

	if a.From != nil {
		object["from"], err = json.Marshal(a.From)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'from': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/applications)
	ListApplications(w http.ResponseWriter, r *http.Request, params ListApplicationsParams)
	// CreateApplication Bewerbung inklusive erstem Ereignis (Vorgemerkt oder Beworben) anlegen
	// (POST /api/v1/applications)
	CreateApplication(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/v1/applications/{id})
	DeleteApplication(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/applications/{id})
	GetApplication(w http.ResponseWriter, r *http.Request, id Id)
	// UpdateApplication Stammdaten ändern (nicht den Status)
	// (PATCH /api/v1/applications/{id})
	UpdateApplication(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/applications/{id}/allowed-events)
	ListAllowedEvents(w http.ResponseWriter, r *http.Request, id Id)
	// AddEvent Statuswechsel als Ereignis erfassen (422 bei unerlaubtem Übergang)
	// (POST /api/v1/applications/{id}/events)
	AddEvent(w http.ResponseWriter, r *http.Request, id Id)
	// UndoLastEvent Letztes Ereignis rückgängig machen
	// (DELETE /api/v1/applications/{id}/events/latest)
	UndoLastEvent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/appointments)
	ListAppointments(w http.ResponseWriter, r *http.Request, params ListAppointmentsParams)
	// ListCompanies Alle Firmen mit Anzahl Bewerbungen
	// (GET /api/v1/companies)
	ListCompanies(w http.ResponseWriter, r *http.Request)
	// CreateCompany Firma anlegen
	// (POST /api/v1/companies)
	CreateCompany(w http.ResponseWriter, r *http.Request)
	// DeleteCompany Firma löschen (nur ohne Bewerbungen, sonst 409)
	// (DELETE /api/v1/companies/{id})
	DeleteCompany(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api/v1/companies/{id})
	GetCompany(w http.ResponseWriter, r *http.Request, id Id)
	// UpdateCompany Firma ändern (nur gesetzte Felder; "" löscht optionale Felder)
	// (PATCH /api/v1/companies/{id})
	UpdateCompany(w http.ResponseWriter, r *http.Request, id Id)
	// GetCv Lebenslauf lesen (leere Struktur, solange keiner gespeichert ist)
	// (GET /api/v1/cv)
	GetCv(w http.ResponseWriter, r *http.Request)
	// SaveCv Lebenslauf ersetzen
	// (PUT /api/v1/cv)
	SaveCv(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/deadlines)
	ListDeadlines(w http.ResponseWriter, r *http.Request, params ListDeadlinesParams)

	// (GET /api/v1/stats/funnel)
	GetFunnel(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/stats/summary)
	GetSummary(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListApplicationsParams

	// ------------- Optional query parameter "phase" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "phase", r.URL.Query(), &params.Phase, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "phase"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "phase", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApplications(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateApplication(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApplication(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApplication operation middleware
func (siw *ServerInterfaceWrapper) DeleteApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApplication operation middleware
func (siw *ServerInterfaceWrapper) GetApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateApplication operation middleware
func (siw *ServerInterfaceWrapper) UpdateApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAllowedEvents operation middleware
func (siw *ServerInterfaceWrapper) ListAllowedEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAllowedEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddEvent operation middleware
func (siw *ServerInterfaceWrapper) AddEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UndoLastEvent operation middleware
func (siw *ServerInterfaceWrapper) UndoLastEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UndoLastEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAppointments operation middleware
func (siw *ServerInterfaceWrapper) ListAppointments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAppointmentsParams

	// ------------- Optional query parameter "within_days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "within_days", r.URL.Query(), &params.WithinDays, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "within_days"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "within_days", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAppointments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCompanies operation middleware
func (siw *ServerInterfaceWrapper) ListCompanies(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCompanies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCompany operation middleware
func (siw *ServerInterfaceWrapper) CreateCompany(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCompany(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCompany operation middleware
func (siw *ServerInterfaceWrapper) DeleteCompany(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCompany(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCompany operation middleware
func (siw *ServerInterfaceWrapper) GetCompany(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCompany(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCompany operation middleware
func (siw *ServerInterfaceWrapper) UpdateCompany(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCompany(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCv operation middleware
func (siw *ServerInterfaceWrapper) GetCv(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCv(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SaveCv operation middleware
func (siw *ServerInterfaceWrapper) SaveCv(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveCv(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDeadlines operation middleware
func (siw *ServerInterfaceWrapper) ListDeadlines(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDeadlinesParams

	// ------------- Optional query parameter "within_days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "within_days", r.URL.Query(), &params.WithinDays, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "within_days"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "within_days", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeadlines(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFunnel operation middleware
func (siw *ServerInterfaceWrapper) GetFunnel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFunnel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSummary operation middleware
func (siw *ServerInterfaceWrapper) GetSummary(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/companies", wrapper.ListCompanies)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/companies", wrapper.CreateCompany)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/companies/{id}", wrapper.DeleteCompany)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/companies/{id}", wrapper.GetCompany)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/companies/{id}", wrapper.UpdateCompany)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/applications", wrapper.ListApplications)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/applications", wrapper.CreateApplication)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/applications/{id}", wrapper.DeleteApplication)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/applications/{id}", wrapper.GetApplication)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/applications/{id}", wrapper.UpdateApplication)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/applications/{id}/events", wrapper.AddEvent)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/applications/{id}/events/latest", wrapper.UndoLastEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/applications/{id}/allowed-events", wrapper.ListAllowedEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/deadlines", wrapper.ListDeadlines)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/appointments", wrapper.ListAppointments)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/stats/funnel", wrapper.GetFunnel)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/stats/summary", wrapper.GetSummary)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/cv", wrapper.GetCv)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/v1/cv", wrapper.SaveCv)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type ListApplicationsRequestObject struct {
	Params ListApplicationsParams
}

type ListApplicationsResponseObject interface {
	VisitListApplicationsResponse(w http.ResponseWriter) error
}

type ListApplications200JSONResponse []ApplicationSummary

func (response ListApplications200JSONResponse) VisitListApplicationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListApplicationsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListApplicationsdefaultApplicationProblemPlusJSONResponse) VisitListApplicationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplicationRequestObject struct {
	Body *CreateApplicationJSONRequestBody
}

type CreateApplicationResponseObject interface {
	VisitCreateApplicationResponse(w http.ResponseWriter) error
}

type CreateApplication201JSONResponse Application

func (response CreateApplication201JSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApplicationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateApplicationdefaultApplicationProblemPlusJSONResponse) VisitCreateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteApplicationRequestObject struct {
	Id Id `json:"id"`
}

type DeleteApplicationResponseObject interface {
	VisitDeleteApplicationResponse(w http.ResponseWriter) error
}

type DeleteApplication204Response struct {
}

func (response DeleteApplication204Response) VisitDeleteApplicationResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApplicationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteApplicationdefaultApplicationProblemPlusJSONResponse) VisitDeleteApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetApplicationRequestObject struct {
	Id Id `json:"id"`
}

type GetApplicationResponseObject interface {
	VisitGetApplicationResponse(w http.ResponseWriter) error
}

type GetApplication200JSONResponse Application

func (response GetApplication200JSONResponse) VisitGetApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApplicationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetApplicationdefaultApplicationProblemPlusJSONResponse) VisitGetApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateApplicationRequestObject struct {
	Id   Id `json:"id"`
	Body *UpdateApplicationJSONRequestBody
}

type UpdateApplicationResponseObject interface {
	VisitUpdateApplicationResponse(w http.ResponseWriter) error
}

type UpdateApplication200JSONResponse Application

func (response UpdateApplication200JSONResponse) VisitUpdateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateApplicationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateApplicationdefaultApplicationProblemPlusJSONResponse) VisitUpdateApplicationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListAllowedEventsRequestObject struct {
	Id Id `json:"id"`
}

type ListAllowedEventsResponseObject interface {
	VisitListAllowedEventsResponse(w http.ResponseWriter) error
}

type ListAllowedEvents200JSONResponse []EventType

func (response ListAllowedEvents200JSONResponse) VisitListAllowedEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAllowedEventsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListAllowedEventsdefaultApplicationProblemPlusJSONResponse) VisitListAllowedEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AddEventRequestObject struct {
	Id   Id `json:"id"`
	Body *AddEventJSONRequestBody
}

type AddEventResponseObject interface {
	VisitAddEventResponse(w http.ResponseWriter) error
}

type AddEvent201JSONResponse Event

func (response AddEvent201JSONResponse) VisitAddEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AddEventdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response AddEventdefaultApplicationProblemPlusJSONResponse) VisitAddEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UndoLastEventRequestObject struct {
	Id Id `json:"id"`
}

type UndoLastEventResponseObject interface {
	VisitUndoLastEventResponse(w http.ResponseWriter) error
}

type UndoLastEvent200JSONResponse Application

func (response UndoLastEvent200JSONResponse) VisitUndoLastEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UndoLastEventdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UndoLastEventdefaultApplicationProblemPlusJSONResponse) VisitUndoLastEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListAppointmentsRequestObject struct {
	Params ListAppointmentsParams
}

type ListAppointmentsResponseObject interface {
	VisitListAppointmentsResponse(w http.ResponseWriter) error
}

type ListAppointments200JSONResponse []Appointment

func (response ListAppointments200JSONResponse) VisitListAppointmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAppointmentsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListAppointmentsdefaultApplicationProblemPlusJSONResponse) VisitListAppointmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListCompaniesRequestObject struct {
}

type ListCompaniesResponseObject interface {
	VisitListCompaniesResponse(w http.ResponseWriter) error
}

type ListCompanies200JSONResponse []Company

func (response ListCompanies200JSONResponse) VisitListCompaniesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCompaniesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListCompaniesdefaultApplicationProblemPlusJSONResponse) VisitListCompaniesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCompanyRequestObject struct {
	Body *CreateCompanyJSONRequestBody
}

type CreateCompanyResponseObject interface {
	VisitCreateCompanyResponse(w http.ResponseWriter) error
}

type CreateCompany201JSONResponse Company

func (response CreateCompany201JSONResponse) VisitCreateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCompanydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateCompanydefaultApplicationProblemPlusJSONResponse) VisitCreateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCompanyRequestObject struct {
	Id Id `json:"id"`
}

type DeleteCompanyResponseObject interface {
	VisitDeleteCompanyResponse(w http.ResponseWriter) error
}

type DeleteCompany204Response struct {
}

func (response DeleteCompany204Response) VisitDeleteCompanyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCompanydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteCompanydefaultApplicationProblemPlusJSONResponse) VisitDeleteCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetCompanyRequestObject struct {
	Id Id `json:"id"`
}

type GetCompanyResponseObject interface {
	VisitGetCompanyResponse(w http.ResponseWriter) error
}

type GetCompany200JSONResponse Company

func (response GetCompany200JSONResponse) VisitGetCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCompanydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetCompanydefaultApplicationProblemPlusJSONResponse) VisitGetCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCompanyRequestObject struct {
	Id   Id `json:"id"`
	Body *UpdateCompanyJSONRequestBody
}

type UpdateCompanyResponseObject interface {
	VisitUpdateCompanyResponse(w http.ResponseWriter) error
}

type UpdateCompany200JSONResponse Company

func (response UpdateCompany200JSONResponse) VisitUpdateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCompanydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateCompanydefaultApplicationProblemPlusJSONResponse) VisitUpdateCompanyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetCvRequestObject struct {
}

type GetCvResponseObject interface {
	VisitGetCvResponse(w http.ResponseWriter) error
}

type GetCv200JSONResponse Cv

func (response GetCv200JSONResponse) VisitGetCvResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCvdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetCvdefaultApplicationProblemPlusJSONResponse) VisitGetCvResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SaveCvRequestObject struct {
	Body *SaveCvJSONRequestBody
}

type SaveCvResponseObject interface {
	VisitSaveCvResponse(w http.ResponseWriter) error
}

type SaveCv200JSONResponse Cv

func (response SaveCv200JSONResponse) VisitSaveCvResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SaveCvdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response SaveCvdefaultApplicationProblemPlusJSONResponse) VisitSaveCvResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeadlinesRequestObject struct {
	Params ListDeadlinesParams
}

type ListDeadlinesResponseObject interface {
	VisitListDeadlinesResponse(w http.ResponseWriter) error
}

type ListDeadlines200JSONResponse []Deadline

func (response ListDeadlines200JSONResponse) VisitListDeadlinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDeadlinesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListDeadlinesdefaultApplicationProblemPlusJSONResponse) VisitListDeadlinesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetFunnelRequestObject struct {
}

type GetFunnelResponseObject interface {
	VisitGetFunnelResponse(w http.ResponseWriter) error
}

type GetFunnel200JSONResponse []FunnelStep

func (response GetFunnel200JSONResponse) VisitGetFunnelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetFunneldefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetFunneldefaultApplicationProblemPlusJSONResponse) VisitGetFunnelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSummaryRequestObject struct {
}

type GetSummaryResponseObject interface {
	VisitGetSummaryResponse(w http.ResponseWriter) error
}

type GetSummary200JSONResponse Summary

func (response GetSummary200JSONResponse) VisitGetSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSummarydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSummarydefaultApplicationProblemPlusJSONResponse) VisitGetSummaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/v1/applications)
	ListApplications(ctx context.Context, request ListApplicationsRequestObject) (ListApplicationsResponseObject, error)
	// CreateApplication Bewerbung inklusive erstem Ereignis (Vorgemerkt oder Beworben) anlegen
	// (POST /api/v1/applications)
	CreateApplication(ctx context.Context, request CreateApplicationRequestObject) (CreateApplicationResponseObject, error)

	// (DELETE /api/v1/applications/{id})
	DeleteApplication(ctx context.Context, request DeleteApplicationRequestObject) (DeleteApplicationResponseObject, error)

	// (GET /api/v1/applications/{id})
	GetApplication(ctx context.Context, request GetApplicationRequestObject) (GetApplicationResponseObject, error)
	// UpdateApplication Stammdaten ändern (nicht den Status)
	// (PATCH /api/v1/applications/{id})
	UpdateApplication(ctx context.Context, request UpdateApplicationRequestObject) (UpdateApplicationResponseObject, error)

	// (GET /api/v1/applications/{id}/allowed-events)
	ListAllowedEvents(ctx context.Context, request ListAllowedEventsRequestObject) (ListAllowedEventsResponseObject, error)
	// AddEvent Statuswechsel als Ereignis erfassen (422 bei unerlaubtem Übergang)
	// (POST /api/v1/applications/{id}/events)
	AddEvent(ctx context.Context, request AddEventRequestObject) (AddEventResponseObject, error)
	// UndoLastEvent Letztes Ereignis rückgängig machen
	// (DELETE /api/v1/applications/{id}/events/latest)
	UndoLastEvent(ctx context.Context, request UndoLastEventRequestObject) (UndoLastEventResponseObject, error)

	// (GET /api/v1/appointments)
	ListAppointments(ctx context.Context, request ListAppointmentsRequestObject) (ListAppointmentsResponseObject, error)
	// ListCompanies Alle Firmen mit Anzahl Bewerbungen
	// (GET /api/v1/companies)
	ListCompanies(ctx context.Context, request ListCompaniesRequestObject) (ListCompaniesResponseObject, error)
	// CreateCompany Firma anlegen
	// (POST /api/v1/companies)
	CreateCompany(ctx context.Context, request CreateCompanyRequestObject) (CreateCompanyResponseObject, error)
	// DeleteCompany Firma löschen (nur ohne Bewerbungen, sonst 409)
	// (DELETE /api/v1/companies/{id})
	DeleteCompany(ctx context.Context, request DeleteCompanyRequestObject) (DeleteCompanyResponseObject, error)

	// (GET /api/v1/companies/{id})
	GetCompany(ctx context.Context, request GetCompanyRequestObject) (GetCompanyResponseObject, error)
	// UpdateCompany Firma ändern (nur gesetzte Felder; "" löscht optionale Felder)
	// (PATCH /api/v1/companies/{id})
	UpdateCompany(ctx context.Context, request UpdateCompanyRequestObject) (UpdateCompanyResponseObject, error)
	// GetCv Lebenslauf lesen (leere Struktur, solange keiner gespeichert ist)
	// (GET /api/v1/cv)
	GetCv(ctx context.Context, request GetCvRequestObject) (GetCvResponseObject, error)
	// SaveCv Lebenslauf ersetzen
	// (PUT /api/v1/cv)
	SaveCv(ctx context.Context, request SaveCvRequestObject) (SaveCvResponseObject, error)

	// (GET /api/v1/deadlines)
	ListDeadlines(ctx context.Context, request ListDeadlinesRequestObject) (ListDeadlinesResponseObject, error)

	// (GET /api/v1/stats/funnel)
	GetFunnel(ctx context.Context, request GetFunnelRequestObject) (GetFunnelResponseObject, error)

	// (GET /api/v1/stats/summary)
	GetSummary(ctx context.Context, request GetSummaryRequestObject) (GetSummaryResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListApplications operation middleware
func (sh *strictHandler) ListApplications(w http.ResponseWriter, r *http.Request, params ListApplicationsParams) {
	var request ListApplicationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListApplications(ctx, request.(ListApplicationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApplications")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListApplicationsResponseObject); ok {
		if err := validResponse.VisitListApplicationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateApplication operation middleware
func (sh *strictHandler) CreateApplication(w http.ResponseWriter, r *http.Request) {
	var request CreateApplicationRequestObject

	var body CreateApplicationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateApplication(ctx, request.(CreateApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateApplication")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateApplicationResponseObject); ok {
		if err := validResponse.VisitCreateApplicationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApplication operation middleware
func (sh *strictHandler) DeleteApplication(w http.ResponseWriter, r *http.Request, id Id) {
	var request DeleteApplicationRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApplication(ctx, request.(DeleteApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApplication")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteApplicationResponseObject); ok {
		if err := validResponse.VisitDeleteApplicationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApplication operation middleware
func (sh *strictHandler) GetApplication(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetApplicationRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApplication(ctx, request.(GetApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApplication")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApplicationResponseObject); ok {
		if err := validResponse.VisitGetApplicationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateApplication operation middleware
func (sh *strictHandler) UpdateApplication(w http.ResponseWriter, r *http.Request, id Id) {
	var request UpdateApplicationRequestObject

	request.Id = id

	var body UpdateApplicationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateApplication(ctx, request.(UpdateApplicationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateApplication")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateApplicationResponseObject); ok {
		if err := validResponse.VisitUpdateApplicationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAllowedEvents operation middleware
func (sh *strictHandler) ListAllowedEvents(w http.ResponseWriter, r *http.Request, id Id) {
	var request ListAllowedEventsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAllowedEvents(ctx, request.(ListAllowedEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAllowedEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAllowedEventsResponseObject); ok {
		if err := validResponse.VisitListAllowedEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddEvent operation middleware
func (sh *strictHandler) AddEvent(w http.ResponseWriter, r *http.Request, id Id) {
	var request AddEventRequestObject

	request.Id = id

	var body AddEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddEvent(ctx, request.(AddEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddEventResponseObject); ok {
		if err := validResponse.VisitAddEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UndoLastEvent operation middleware
func (sh *strictHandler) UndoLastEvent(w http.ResponseWriter, r *http.Request, id Id) {
	var request UndoLastEventRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UndoLastEvent(ctx, request.(UndoLastEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UndoLastEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UndoLastEventResponseObject); ok {
		if err := validResponse.VisitUndoLastEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAppointments operation middleware
func (sh *strictHandler) ListAppointments(w http.ResponseWriter, r *http.Request, params ListAppointmentsParams) {
	var request ListAppointmentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAppointments(ctx, request.(ListAppointmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAppointments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAppointmentsResponseObject); ok {
		if err := validResponse.VisitListAppointmentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCompanies operation middleware
func (sh *strictHandler) ListCompanies(w http.ResponseWriter, r *http.Request) {
	var request ListCompaniesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCompanies(ctx, request.(ListCompaniesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCompanies")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCompaniesResponseObject); ok {
		if err := validResponse.VisitListCompaniesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCompany operation middleware
func (sh *strictHandler) CreateCompany(w http.ResponseWriter, r *http.Request) {
	var request CreateCompanyRequestObject

	var body CreateCompanyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCompany(ctx, request.(CreateCompanyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCompany")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCompanyResponseObject); ok {
		if err := validResponse.VisitCreateCompanyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCompany operation middleware
func (sh *strictHandler) DeleteCompany(w http.ResponseWriter, r *http.Request, id Id) {
	var request DeleteCompanyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCompany(ctx, request.(DeleteCompanyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCompany")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCompanyResponseObject); ok {
		if err := validResponse.VisitDeleteCompanyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCompany operation middleware
func (sh *strictHandler) GetCompany(w http.ResponseWriter, r *http.Request, id Id) {
	var request GetCompanyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCompany(ctx, request.(GetCompanyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCompany")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCompanyResponseObject); ok {
		if err := validResponse.VisitGetCompanyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCompany operation middleware
func (sh *strictHandler) UpdateCompany(w http.ResponseWriter, r *http.Request, id Id) {
	var request UpdateCompanyRequestObject

	request.Id = id

	var body UpdateCompanyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCompany(ctx, request.(UpdateCompanyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCompany")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCompanyResponseObject); ok {
		if err := validResponse.VisitUpdateCompanyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCv operation middleware
func (sh *strictHandler) GetCv(w http.ResponseWriter, r *http.Request) {
	var request GetCvRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCv(ctx, request.(GetCvRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCv")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCvResponseObject); ok {
		if err := validResponse.VisitGetCvResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SaveCv operation middleware
func (sh *strictHandler) SaveCv(w http.ResponseWriter, r *http.Request) {
	var request SaveCvRequestObject

	var body SaveCvJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SaveCv(ctx, request.(SaveCvRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SaveCv")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SaveCvResponseObject); ok {
		if err := validResponse.VisitSaveCvResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDeadlines operation middleware
func (sh *strictHandler) ListDeadlines(w http.ResponseWriter, r *http.Request, params ListDeadlinesParams) {
	var request ListDeadlinesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDeadlines(ctx, request.(ListDeadlinesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDeadlines")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDeadlinesResponseObject); ok {
		if err := validResponse.VisitListDeadlinesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFunnel operation middleware
func (sh *strictHandler) GetFunnel(w http.ResponseWriter, r *http.Request) {
	var request GetFunnelRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFunnel(ctx, request.(GetFunnelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFunnel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFunnelResponseObject); ok {
		if err := validResponse.VisitGetFunnelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSummary operation middleware
func (sh *strictHandler) GetSummary(w http.ResponseWriter, r *http.Request) {
	var request GetSummaryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSummary(ctx, request.(GetSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSummary")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSummaryResponseObject); ok {
		if err := validResponse.VisitGetSummaryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fvdcts29n8VDP+9sOdPy7LjbKfO7Ow4jpNJm+16orQXTbIakDwiUYEAA4By7azeZC/zDHvVO7/YDgh+",
	"E5QoWVba2ZtEJIGDg9/5wDkHx58dn8cJZ8CUdM4/OwkWOAYFInt6Heh/CXPOnQSryHEdhmNwzh0SOK4j",
	"4FNKBATOuRIpuI70I4ixnjHjIsbKOXfSNBupbhM9SypBWOgsl0s9WSacScjWuRbcoxDrnz5nCpjSP3GS",
	"UOJjRTg7TsyI//9Vcqa/VWt9I2DmnDv/d1xt5Nh8lccF3WzFAKQvSKLJOefOS4goCMSwH6G3Ly/Rd2dP",
	"v3X0sHyuJn1RMaAfE8ETEIoYnvVymN1OSTBgx2453AD42TJAAFYQTLFq0AuwgiNFYrARhUUhN6Igluvg",
	"uNLDnWVJCAuBb/XzwD38yr1pKqiVfcoroDofGVcgrV+SCEtYK8ZskB7NJdGLTBVR1A6j5Knwez4prNJh",
	"IL3Tc5eukybBhkJZ1u3ivTGUmqq0FKGzpZLLApqGYjQYKsX/sWSCe7+Cn0m4prqvWZKqB+vvjAipptmK",
	"6xD8EW5KTaupTIx/ewMsVJFzfjIej93VOlQbfWodXOpUbeRTO92u2tTmPNFTYsJK3txVStXcxDrpNwTf",
	"kXQd0jUyvMbKj/T6TSf2YypQCBLUnQL0EmgAAt2ACIChEO6/sACEeoaAMEQBBAg0yfhE9P4/0o9U9oVn",
	"xDAFmVEYOe7DFOV/T+KrBDdJ4xiL28c/PgbSobhQuSlnjRnar9hm8ATYNEhh6Pjde/Q/p9tueOom7D3G",
	"zglTce5fm8pSi4R2pjCZ/IYI1LBtXm8gA8IUiAWBm6ngKQtqPOgvIYhB4m/JpQXEerHUmM+3bAP/0lBZ",
	"DbzPUyOb7ja2id0GyrFXfv0x1Q14kqgBaGYr5sg1oozutleg1hNfFIy33foax7uBk6/tszl4nXVnrK3Y",
	"0dc8bf9gsHUhWnSBeQMeMElxOhshYAGaQUQV+ivyiEQRpApGqPKG6IaIAHlAYjRJgPgRCIZIyLggINQI",
	"TTjFLAQ013BVlDXy+XCFiFQuogRm+uHV1TsNLRjUNejpXKUCHSQgJGcjjWj2zUVviFTA8gceMajxddiV",
	"BQRpFZ4MyrAuF1flnKWr8X1tpp2Ou1kX/JaAIMB82IR+NamxwBPLAhrIFIcgN6D/Jp/TpH5ioW7gXU/x",
	"2oxbZuhqNdqEnWszZT2Yck4o3YTyRE94JXiaDCBeRXHNONJmXw8OPnJgGwri1pSx3GwN0bqwrZ6tppgd",
	"Vx1AKGAbrxOAwoTKYbE+sGC9VK5BEB6Y+EEqotK+7GANZ1JhoYYv15JADkiTiYJoD7wNY275kc12HpEw",
	"oiSMWoayxlk3zPWpxRlskmpxEWJG7vCW6AtOYe9CyxZtsV7QbIBqF2Dp+Drio7Uv7WxwzY4oLIBuPK+1",
	"sXL9gl7PBgib25j3tuDAdbop/NPN+dZLG1J2lnNJdgKK73EkENfxlf519HfOsHLR3Qg9H6HT8emZ+aZ/",
	"HY2fOK6TYKVA6Jn//PAh+Hy2PDg6GL8/Ofru479O3o+PTj8eHv7tG1t0XZ5OXZuNMaGDbCUCHFDCYNBg",
	"Sth8o+NYC3XtUbxZGWW7CDOJONuiBJanF2bfPVqQn/GWc6mmFG2Gd7g1BX7EOOUhgV6Xe7LG5drChh4b",
	"GgRYgyc7brUIpltewgpCLm5tu1iDRrn7bWA468DQ2l7JWLGQbW8vaia1h0rI8OLWlrUQvgARpPXVPc4p",
	"YPYVaiBmsxVPNvyvFtYy1DZljg3AHSjPQYUlxpVd2Nz3UyEgGMrUhrK2VVhy5OsrN+otvRJ4l68NLI01",
	"tZ+5CCEGMVeO6zyHGy480LQmvgBghIWvQCYCgx85rnMZYUqBhXAlIkwVsPq7Cy+EEMzs1wWejuv8AIwB",
	"oyCYwqHjOhcsBI+rGon8jf6P8ThuvPNCoBAxzd2FJ03E8ksqUvDnIdzxMBv8AxAGb/W7GGiQstD5aIH9",
	"ZcoY0IkCi28TncolTz1akx5LY8+ogQDsR9CjI1LlQd1qezPDKlquYcAmtfLmq3uUlWbQrSl5QFAlWhd1",
	"JIdSFqCWKBAIilNPY71WhwtjWF8b2q91WAzDhup1caNQswMPBBCltcd1LuaKLDKdC0H6EeVSArNqVa3P",
	"AAcBMaW465qgTCND68hRCuJEQbCRyzepsdUFzQjQwP5F8HijVaq7ka5699+oFFKrXK0gRwJmIPJaw2qD",
	"yMXWuvmwSe4t6F+Es8uidt6+BOstqW910rYYbRx8/XXsSXbXN1FYyS6L2Wnb50FylzAtj6TVw/hsBsI+",
	"pLdtoe2MzDi35MvGRHtF66b7LiZXbhgvwmmAb+VU8WnRwTPQFXu302qTg7KfulwsTSsxBASzbdkRhWrK",
	"KZ4pEIO5aum0hTHDSdCvNIbR6eBzzBYA5qIvVmqTtWywLoKuRiyzyGrGu0fUzyBuMNW+Fi04Q8/hBoSX",
	"shDYCH0PQXbPoT3ADfiRBGrq+5hKdCWAhIzIeun+GdIT8FylQCnkMxGIkHgKSeJHCKcSBRCju5TqmxYE",
	"YoZlVrYv6I1Q3ryVX77otfp6xdBB0dx1iELIrwxGH1jpv86dckPy6J3A/hwEurh+7bjOAoQ0EJyMxqNx",
	"cRmOE+KcO09G41FeeogynTnGCTlenBzXOMneh5B5OG1i2UvdU+foi4iL+kC30Xn3Pm+6+5RClinlXXfF",
	"1fLA5rds9HLp2omVF9bDqDW8bFtFJqkfASIMvSQiBpbduOiYZaK0lJkiKisE2dj41OBgTfFi+bHVOHg6",
	"Hq9oGuw2Cw6ycEv7RsfKuw2FNbtwS+Ut7wUB3aUgpDKhwQyntLfQWW6w1r7oOgqHWjGchtZ8NOmjRcEu",
	"s/SiNjjv1wSpnvPgdiPQBmJl7oGXTW+lA6plR2gnj7G+TSg6aKYQbg97efNTyRcRNqepJAtAWqIQV47u",
	"oArjTYmySNIOEWYUTALUI8mla3Uhx59JsDROmYKCrqRfZO/bkm7AfdZ16q8gv5XevUJaHd4rUCtZHO9L",
	"IyoxxkSVkjt6R2LIKk67t8+mX7dRrIYcvw4c7eSSogOhieJP2dXiXq3a9EIMsuq9yfBV4VV3YNYTheNY",
	"o8qQIcrQASO6XUOHFiY+OdzOao8xpfwGgqOqTbs/GDBDr8zIfZxyjTxy3eF2QSX68f6LH0kFsig9QGk+",
	"ejr7Q5jOSnlUctjOKK0n7UVgpPZIplg1U+/3YK0t2lSFKxOP78b0amlDI2MwQT8wdHB2epoVyFJWaF2M",
	"7v/tgb7lDbc1TKMIxxQrkGrV4foTC/gbLFUl4a99amV/sKLzo7f3v/vz8P4LC0kY62yf7UAkb7Lmtpog",
	"RG0VlC/zmBZb9MCuTZ2qgZ1Vm9D9AkQJnMYIe6YZDR1MFGYBFgE6OTvsSUtuiIqIKS60ExQSp7Fz/uQv",
	"T7ObNPM0djuJ/t5ylQKJQX6cSQURsADQOxDxLgKeF1hGHsciaBqduZQisFqQl+WofYBVtPkOAMoksi7C",
	"NImwB4pIHQU92L4udNHD0M7izwt2hyNar6nUrKsCZ12eV2zscY6gRp/vno+hUmSPmttpiWBLilaXgE23",
	"ByZndfE8fmLW3pahp89SlgrT9dqoVUjOpEJn4+8Oe3WvL6Xr3dh4HwqQbe/B/qtlZTvP1vZim18lS1sh",
	"ml1maEaLq+Ss24X/DH1wPjhln33ZY59/Phxg0YveY0qr+eJRNXxhQ7DqfN9JWFcQQxSysLrZK6+dQNV1",
	"D6LdbN9AcGEMJbVgNcELuFw8lqov9q7gC7tul9jsVjQgtFYDa4Nd09Mgb4xaHVW9KEc9IDb+9vAZuv/d",
	"AzG7/0IpCQG9FObPJyRhASJxDAIBU2VnyJ85jC4QGxIa/mM2A1ai8Vjxs1RYyeNZ1gazyjeZRpm9hM+1",
	"npwhEXQ2+mii0tljo1T784w+mIqLnEf0FsUSFix0W5UO9HcNRPX+szV/qQyxOve6t3e1aDC7tSuSfwnV",
	"/Eam3yWRVWT09a06LwzDLTJMN6uiEqnIvKJXbaNLrHb0VfwvdKngvwMA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
