/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GmailMessageId } from '../../models/gmail-message-id';
import { ProcessedMail } from '../../models/processed-mail';

export interface AgentGetProcessedMail$Params {
  messageId: GmailMessageId;
}

export function agentGetProcessedMail(http: HttpClient, rootUrl: string, params: AgentGetProcessedMail$Params, context?: HttpContext): Observable<StrictHttpResponse<ProcessedMail>> {
  const rb = new RequestBuilder(rootUrl, agentGetProcessedMail.PATH, 'get');
  if (params) {
    rb.path('messageId', params.messageId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProcessedMail>;
    })
  );
}

agentGetProcessedMail.PATH = '/api/agent/processed-mails/{messageId}';
