/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProcessedMail } from '../../models/processed-mail';
import { ProcessedMailInput } from '../../models/processed-mail-input';

export interface AgentMarkMailProcessed$Params {
      body: ProcessedMailInput
}

export function agentMarkMailProcessed(http: HttpClient, rootUrl: string, params: AgentMarkMailProcessed$Params, context?: HttpContext): Observable<StrictHttpResponse<ProcessedMail>> {
  const rb = new RequestBuilder(rootUrl, agentMarkMailProcessed.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProcessedMail>;
    })
  );
}

agentMarkMailProcessed.PATH = '/api/agent/processed-mails';
