/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Suggestion } from '../../models/suggestion';
import { SuggestionInput } from '../../models/suggestion-input';

export interface AgentCreateSuggestion$Params {
      body: SuggestionInput
}

export function agentCreateSuggestion(http: HttpClient, rootUrl: string, params: AgentCreateSuggestion$Params, context?: HttpContext): Observable<StrictHttpResponse<Suggestion>> {
  const rb = new RequestBuilder(rootUrl, agentCreateSuggestion.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Suggestion>;
    })
  );
}

agentCreateSuggestion.PATH = '/api/agent/suggestions';
