/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AgentApplication } from '../../models/agent-application';
import { DocumentsState } from '../../models/documents-state';

export interface AgentListApplications$Params {
  documents_state: DocumentsState;
}

export function agentListApplications(http: HttpClient, rootUrl: string, params: AgentListApplications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AgentApplication>>> {
  const rb = new RequestBuilder(rootUrl, agentListApplications.PATH, 'get');
  if (params) {
    rb.query('documents_state', params.documents_state, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AgentApplication>>;
    })
  );
}

agentListApplications.PATH = '/api/agent/applications';
