/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OpenApplication } from '../../models/open-application';

export interface AgentListOpenApplications$Params {
}

export function agentListOpenApplications(http: HttpClient, rootUrl: string, params?: AgentListOpenApplications$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OpenApplication>>> {
  const rb = new RequestBuilder(rootUrl, agentListOpenApplications.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OpenApplication>>;
    })
  );
}

agentListOpenApplications.PATH = '/api/agent/applications/open';
