/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CvReview } from '../../models/cv-review';
import { CvReviewResult } from '../../models/cv-review-result';

export interface AgentCompleteCvReview$Params {
  id: string;
      body: CvReviewResult
}

export function agentCompleteCvReview(http: HttpClient, rootUrl: string, params: AgentCompleteCvReview$Params, context?: HttpContext): Observable<StrictHttpResponse<CvReview>> {
  const rb = new RequestBuilder(rootUrl, agentCompleteCvReview.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CvReview>;
    })
  );
}

agentCompleteCvReview.PATH = '/api/agent/cv-reviews/{id}';
