/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FunnelStep } from '../../models/funnel-step';

export interface GetFunnel$Params {
}

export function getFunnel(http: HttpClient, rootUrl: string, params?: GetFunnel$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FunnelStep>>> {
  const rb = new RequestBuilder(rootUrl, getFunnel.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FunnelStep>>;
    })
  );
}

getFunnel.PATH = '/api/v1/stats/funnel';
