/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Summary } from '../../models/summary';

export interface GetSummary$Params {
}

export function getSummary(http: HttpClient, rootUrl: string, params?: GetSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<Summary>> {
  const rb = new RequestBuilder(rootUrl, getSummary.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Summary>;
    })
  );
}

getSummary.PATH = '/api/v1/stats/summary';
