/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Appointment } from '../../models/appointment';

export interface ListAppointments$Params {

/**
 * Zeitraum ab heute (Standard 14)
 */
  within_days?: number;
}

export function listAppointments(http: HttpClient, rootUrl: string, params?: ListAppointments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Appointment>>> {
  const rb = new RequestBuilder(rootUrl, listAppointments.PATH, 'get');
  if (params) {
    rb.query('within_days', params.within_days, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Appointment>>;
    })
  );
}

listAppointments.PATH = '/api/v1/appointments';
