/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Deadline } from '../../models/deadline';

export interface ListDeadlines$Params {

/**
 * Zeitraum ab heute (Standard 7); überfällige Fristen sind immer enthalten
 */
  within_days?: number;
}

export function listDeadlines(http: HttpClient, rootUrl: string, params?: ListDeadlines$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Deadline>>> {
  const rb = new RequestBuilder(rootUrl, listDeadlines.PATH, 'get');
  if (params) {
    rb.query('within_days', params.within_days, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Deadline>>;
    })
  );
}

listDeadlines.PATH = '/api/v1/deadlines';
